#import "../lib.typ": *

== From Interpellation to Performativity

#textcite(<Butler1990Gender>, <Butler1988Performative>) points out that gender is not what we intrinsically "are," but what we constantly "do." It is not a stable essence, but an effect produced by the "stylised repetition of acts in time." There is no pre-existing "doer" behind the deed. On the contrary, it is the deed itself, in its constant repetition, that fictitiously constitutes and consolidates the illusion of a stable "doer." I found that many of my actions perfectly illustrate this theory.

In informal settings, I used Latin letters or cursive script for my signature to make my name ambiguous. In my artificial intelligence class, I changed the dataset. These were secret performative acts about the name. I even used that feminine name myself, and if discovered, I would blame the "mistake" on the input method. This series of performative acts -- using an ambiguous signature, altering the dataset, and blaming the input method -- is precisely what Judith Butler describes as the "stylised repetition of acts." They are not expressions of an inner essence but produce the effect of identity through constant reiteration in a specific social context.

My feeling happy when praised by friends as "quiet" and "virtuous" was also a performative citation of the script of traditional femininity. Making a bracelet and enclosing a note with delicate handwriting, the "King" in the game said they thought their "angel" would be a girl, and I "secretly felt extremely delighted." These are not passive reactions, but a series of active, "stylised acts." By repeating these acts that conform to social imaginings of "femininity," I produced the effect of a female gender identity.

A strong sense of pleasure always accompanied these moments of successful performative act. The source of this pleasure is key to understanding Butler's theory. When friends defended my feminine name, when someone thought I am female, and especially when the junior female student replied, "Wow, a pretty sis," I felt delighted. This gender euphoria is not the joy of an inner, "true" self being seen -- that view still falls into the trap of essentialism. Instead, this pleasure is the profound satisfaction and relief that comes after a successful performative utterance. At that moment, the social world reflects and confirms the identity that my actions sought to create. It is the joy of making a fiction feel real, the satisfaction of successfully bringing a social reality into existence.

This discourse also plunged me into a brief confusion: if gender is performative, then what is my gender identity, and where did it come from? Is it also the result of performative acts at a younger age? I began to try to reflect on all gender-related matters in my upbringing, trying to understand how my gender identity was constructed.

My desire for a feminine name may not have been fabricated out of thin air, but like a ghost, had long been lurking in my life, stemming from the experience of my name being frequently misspelt or mistyped by others in my childhood. Also, adults said that my "personality was like a little girl's," probably because I liked playing with stuffed animal toys and disliked sports and fighting. I was also punished for imitating a little girl on TV covering her mouth to laugh, being told, "Boys can't laugh like girls."

Whether it is an input method error or the correction of behaviour, it is the continuous interpellation of the ideological state apparatus. #textcite(<Althusser1971Ideology>) describes interpellation as the process by which ideology "hails" individuals and constitutes them as subjects, like a policeman shouting on the street: "Hey, you there!" Every misuse of a name, every disciplining of behaviour, is an interpellation from the social machine: "Hey, the little girl there!"

Input methods are not a neutral technology, but rather an ideological state apparatus that actively manages and shapes the subject. Algorithms replace traditional institutions as the initiators of "interpellation." Unlike traditional state apparatuses, algorithms do not require natural persons, nor do they possess malice; they simply execute instrumental rationality programs like Adolf Eichmann -- even more faithfully than Eichmann, because they are not a biological organism, which do not tire and feel no pain. When it recommends words according to preset word frequencies, it systematically excludes rare Chinese characters and disciplines those who use them. It sets the most probable language patterns as standards, and this technology, in turn, shapes users' language habits, a form of forced assimilation of human behaviours. Recent studies show that Large Language Models are playing similar roles in the English-speaking world @Sourati2025Shrinking@Yakura2025Empirical.

Initially, my reaction to this call was anger and rejection. I was eager to correct it every time, trying to maintain the integrity of my identity as a "boy." This reaction is certainly not, as conservatives claim, because I have a boyish self within me, but rather a product of being disciplined by another discourse and power (patriarchy). I am neither a transgirl being misgendered nor a boy reacting to childhood trauma, but a fragmented subject torn apart by different symbolic systems, different discourse systems, different power structures, and different ideological state apparatuses.

The initial seed of my feminised identity did not come from some _a priori_ inner essence, but from a systematic "error" -- a product of an input method algorithm, a technological noise. This origin negates the Cartesian, Western Enlightenment narrative of "finding the true self." The construction of identity is sometimes not a heroic journey of self-exploration, but more like an opportunistic, creative use of system loopholes and contingencies. The generation of queer identity may often occur in the cracks, glitches, and noises of the normative system. It is a form of bricolage, not an architect's creation. The trajectory of emotion, from initial anger at the "wrong" interpellation to the eventual joyful acceptance of an alternative subject position, reveals the core of ideology's operation. Ideology is not a cold set of ideas, but a power that orchestrates, manages, and even produces emotion. When mainstream ideology fails to provide emotional comfort, an alternative, marginal call can bring liberating pleasure, because it happens to bridge the pre-existing, ineffable gap between emotion and social positioning.

We can see a dynamic feedback loop between Althusser's interpellation and Butler's performativity. Initially, an interpellation from the external world (like the misspelt name) provides an ideological "script." Then, the subject actively "adopts" and "performs" this script through a series of stylised, repetitive acts (like deliberately blurring a signature, cooking, making a bracelet). These successful performative acts, in turn, elicit new, more precise interpellations from others (like the address "pretty sis"), and these new interpellations further strengthen the subject's desire to continue performing.

Foucault called his analysis of the operation of power "the microphysics of power," and similarly, this cycle of interpellation and performativity can be called "the cybernetics of subject." Gender construction is thus a never-ending circular process: we are interpellated into a specific subject position (Althusser), then we consolidate and inhabit these positions through performativity (Butler), and our actions in turn invite more interpellations. Identity is not a destination to be reached, but a continuous, dynamic process of negotiation between action and response.

== A Pair of Shoes

If the interpellation of a name was a relatively gentle negotiation at the symbolic level, the "girls' shoes" incident was a cruel disciplinary practice inscribed upon the body. This memory is an excellent model for understanding Foucauldian power: power does not always oppress in a grand, visible, monarchical way; it more often exists in a micro, diffuse form of discipline aimed at producing "docile bodies" @Foucault1977Discipline.

These shoes were far more than just a colour and style; they were a strictly encoded gender symbol in the school. They were part of the school uniform. In all occasions requiring a uniform, girls were required to wear the red version and boys the blue one. Therefore, in this micro-society, "red shoes are for girls" was not a debatable opinion, but an unquestionable "truth." By wearing red shoes, I blatantly violated the established norm. My body, because of these shoes, became an "abnormal," transgressive body, exposed to the gaze of disciplinary power.

The power that executed the punishment did not come from the "monarchical" authority of the principal or teachers, but was diffused among the peer group. A few boys snatched my shoes and threw them away, pulled down my pants, and pushed me onto the broken branches of a bush in the garden. These acts of bullying were a cruel, decentralised enforcement of gender norms. The classmates at that moment acted as guards in a prison; they were the most terminal and effective nodes of the power network. The punishment was directly applied to my body: the shoes were stripped away, the body was exposed, and the skin was pierced. This precisely confirms Foucault's assertion: the target of disciplinary power is the body. It operates on the body, shaping it into a compliant "docile body" through training, marking, and punishment.

This micro-power operates not only by punishing transgressors but also by constantly reproducing gender through the "truth mechanisms" within the group. I recall that the boys in my class often established hierarchies through fighting, and I preferred to play with the girls because their interactions seemed more friendly. This preference did not stem from any innate gender essence but was a reaction to two different regimes of discipline. During a museum visit, this difference was dramatically displayed: the boys' group responded to failure with ridicule and expulsion, a punitive practice aimed at eliminating the weak and reinforcing competitive norms; the girls' group, on the other hand, offered encouragement to those who failed, a technology of care aimed at maintaining the collective and emphasising cooperation. My "envy" at that moment was a subject's longing for a more attractive subject position within two different micro-power networks. This reveals that the gender divide is not only marked by symbols like clothing, but is also continuously reproduced through distinctly different behavioural norms, emotional patterns, and power technologies. The power here is not only oppressive, but it also produces a girl's subjectivity in my body.

Faced with this violence inscribed on the body, psychological resistance unfolded peculiarly. I often dreamt of losing my feet in an accident and would feel a strong sense of comfort and relief upon waking. It is a profound psychological metaphor: since the feet wearing "girls' shoes" were the source of social punishment and pain, removing these "girls' feet" was a fantasy of liberation from the grasp of power. It was a complete refusal to become the "docile body" that the system demanded. This experience provides a powerful, non-essentialist genealogical explanation for the emergence of body dysphoria. It shows that body dysphoria does not necessarily stem from a pre-social, innate sense of mismatch. Instead, it can be the direct consequence of disciplinary power violently inscribing social meaning ("girlish") onto the body. Dysphoria arises when this inscription is so painful that the subject internalises it as an alienation from their own flesh. I initially had no aversion to my body. Still, when a part of it (my feet) became the target of social punishment because of its association with a "transgressive" gender symbol (red shoes), I developed a psychological desire to get rid of that body part, seeing it as a foreign object. This localised sense of alienation may be the origin of a more widespread body dysphoria. This "dysphoria" is the scar left on the psyche by normalised violence.

== The Heterotopia of Childhood

The operation of power is not only inscribed on the body but also divides and encodes space. My childhood memories related to the girls' bathroom reveal how this space became what #textcite(<Foucault1986OtherSpaces>) called a "heterotopia" -- a real place that is nevertheless outside of all other places, an "other space." The girls' bathroom was not a neutral, functional place, but a symbolic domain full of contradictory meanings, where the conventional logic of power was suspended, inverted, and reconfigured.

In elementary school, I was playing tag with a few girls, and they repeatedly ran into the girls' bathroom to hide. I stood guard at the door, waiting to catch them when they came out, but a teacher saw me and scolded me. Here, power was not about upholding the rules of the game, but about maintaining the gendered segregation of space. The punishment I received was not for disrupting the game, but because my male body "lingering" outside a space coded as female constituted a potential threat to the spatial order.

Another incident was when a maths teacher used "cleaning the girls' bathroom" as a punishment for mischievous boys. This act was highly symbolic. It transformed a private space usually associated with femininity and "impurity" into a public theatre of punishment. The boys were forced to enter this forbidden zone, and the punishment lay not only in the hard labour but also in the "humiliation" of being forced to cross a gender boundary. Here, space was used as a disciplinary technology, reinforcing the norms of masculinity through forced "effeminacy" -- that is, "real boys" do not belong here.

Finally, at certain times, it offered care that violated the rules. Once, I got sick and vomited during class. Perhaps because the teacher was female, our classroom was close to the girls' bathroom, and it was during class time, when no one was there, the teacher took me to the girls' bathroom to clean the vomit off my clothes and body. In my most vulnerable moment, all the taboos of this space were temporarily lifted. In a state of bodily crisis, the strict rules of gender segregation gave way to a more pressing ethic of care, creating a "state of exception" that instantly transformed this forbidden space into a caring, healing place.

The superposition of these three memories constructs the girls' bathroom as a paradoxical heterotopia. It was simultaneously a safe zone for girls, a place of degradation for boys, and a place of care that could be transgressed in a crisis. It was both a symbol of strict gender order and proof that this order could be broken. This chaotic, contradictory meaning, in a pre-linguistic way, shaped the female space, female symbols, and even femininity itself in my mind into a complex amalgam of fascination, taboo, safety, and care, profoundly influencing my early perception of gender.
