#import "cupst.typ": *

#show: cupst.with(
  title: [For Gender Abolition -- A Scientifically Informed Argument],
  short-title: [],
  
  authors: (
    (
      name: "Jiao Sun",
      affiliation: "affi1",
      email: "j.sun@pgr.reading.ac.uk",
      orcid: "0000-0002-5028-8132",
    ),
  ),
  affiliations: (
    (id: "affi1", name: "Division of Ecology and Evolutionary Biology, School of Biological Science, University of Reading, Whiteknights, Reading, RG6 6EX, United Kingdom"),
  ),
  
  abstract: [
    This article develops an argument for gender abolition through a critique of gender identity informed by neuroscience and the philosophy of mind. I first argue that an identity defined through socially constructed gender categories depends on acquiring their social content. This conceptual argument is distinct from the question of how that content becomes part of an immediate sense of self. Drawing on predictive processing and experiments involving body-ownership illusions and altered footstep sounds, I propose an account of how culturally learned gender associations shape pre-reflective self-perception. I then argue that socially shared categories can enter recursive cultural learning and reinforce the combinations they name, giving those combinations an unequal capacity for cognitive reproduction. Multiplying labels does not by itself remove this asymmetry. On the proposed account, eliminating the associations that sustain contemporary pre-reflective gender identity would undermine its reproduction, although historical labels and voluntary affiliations could survive. Finally, I distinguish the disappearance of categories from the losses that a transition may impose on existing people. I defend gender abolition as a political project whose justification requires weighing these losses against the costs of continuing to reproduce gendered classifications, while recognising the experiences and healthcare needs of contemporary transgender people.
  ],
  
  keywords: ("Gender abolitionism", "gender identity", "gender studies", "philosophy of biology", "criticism of queer theory", "philosophy of mind"),
  
  // Article settings
  manuscript: "article",  // article, rescience, data, software, editorial, proceedings, poster
  layout: "preprint",     // preprint, publish
  
  // Display options
  show-line-numbers: false,
  section-numbering: true,
  structure-color: rgb(33, 63, 144),

  serif-fonts: ("Linux Libertine", "Libertinus Serif", "Noto Serif CJK SC"),
  sans-fonts: ("Source Sans Pro", "Source Sans 3", "Noto Sans CJK SC"),
)

= Introduction

Debates surrounding gender often move between accounts of gender identity as an inherent feature of the individual and accounts of gender as socially constructed. In essentialist versions of the former, a "born this way" narrative locates the basis of social identity in an inner essence. Conversely, post-structuralist queer theory, exemplified by the work of #textcite(<Butler1990Gender>), approaches gender through social construction and performativity. These positions are internally diverse and do not exhaust the available theories. My concern is with a commitment that can survive either approach: treating gender as a central category through which human differences should be understood and organised. I call this commitment "gender-centrism."

I will develop an argument for gender abolition by distinguishing three questions: what makes gender identity meaningful, how it becomes pre-reflective, and whether the social conditions that reproduce it should be preserved. Definitions bear on the first question; neuroscience and the philosophy of mind inform the second; the third requires an additional political and ethical argument. My aim is to defend the freedom to combine bodily features, activities, aesthetics, and personality traits without organising them through gender. This is compatible with distinguishing sex in a strict gametic sense from the wider collection of traits described as masculine or feminine. However, the argument here concerns the social organisation of these traits, rather than a complete account of their biology.

= Gender identity and socially acquired content

To develop this argument, I begin with what gender identity is said to represent. Before asking how it develops in the brain, we must ask whether the content of such an identity can be available independently of society.

// todo: copied to aeg {

#textcite(<APADictGenderIdentity>) defines gender identity as "a person's psychological sense of self in relation to their gender." #textcite(<APADictGender>) defines gender as "the socially constructed roles, behaviors, activities, and attributes that a given society considers appropriate for different genders."

These definitions make gender identity dependent on the social meaning of gender. To understand oneself in relation to a gender, one must first learn what that category means in one's society. Without this learning, the roles, behaviours, and attributes through which one identifies with it are not yet available as the content of that identity. Therefore, gender identity cannot precede the acquisition of the social gender categories.

// } todo: copied to aeg

The inference contains a premise that should be explicit: an identity whose content is one's relation to a particular social category requires access to enough of that category's meaning to distinguish it from other categories. This access need not take the form of a verbal definition or a conscious judgement. It can be acquired through participation in social practices, including before a child can name the category. If a person has no access to the relevant social content at all, their experience cannot yet have that specific content. In this sense, an identity defined through socially constructed gender cannot be innate independently of acquiring gender concepts.

This is a conceptual argument, not an inference from the experiments discussed below. It does not establish that every bodily feeling, disposition, or developmental contribution to gender-related experience is learned. Nor does it show that a particular stereotype, such as an association between women and pink, is necessary for every gender identity. What follows at this stage is dependence on meaningful social content. Which content sustains contemporary gender identity, and how it comes to be experienced, require further argument.

= A Neurocognitive Account of Gender Identity

This conceptual argument leaves a further question: how does something learned from society become an immediate sense of who we are? To answer it, I turn to the neurological processes through which experience shapes self-perception.

I suggest that we describe this experience as "pre-reflective". The term concerns how a process operates: through embodied habits, rapidly and without deliberate reflection. "Innate", on the other hand, concerns how that process originated. What we learn can become so automatic that we no longer experience the learning behind it. Research on cultural influences on automatic cognition provides many examples of this @Gutchess2006@Kitayama_2010@Mason_2010@Qu_2021.

Predictive processing (PP) offers a promising explanation for this transition. On this account, experience informs predictions that operate without our awareness of making an inference @Clark2013Whatever. Two experimental studies help us examine gendered self-perception within this framework.

#textcite(<Tacikowski2020Fluidity>) used the full-body ownership illusion @Petkova_2008. Participants lay down while wearing a VR headset, saw another body from a first-person perspective, and received synchronous or asynchronous touch on corresponding body sites. Under synchronous stimulation, most participants developed a strong illusion that the seen body was their own. Under asynchronous stimulation, the illusion was weak or absent.

Using this technology, the authors conducted three experiments to test whether temporarily "borrowing" an opposite-phenotypic-sex body would shift gendered self-perception.

Experiment 1 measured explicit self-report. After inducing ownership of an opposite-phenotypic-sex body, participants rated current masculinity-femininity. Women reported feeling less feminine and men reported feeling less masculine. Stronger illusion strength predicted larger shifts toward the opposite category.

Experiment 2 used the Implicit Association Test (IAT), which is less easily consciously controlled @Greenwald_1998. It infers implicit self-gender association from reaction-time asymmetries in self-plus-male versus self-plus-female pairings. Under a strong body-ownership illusion, implicit self-gender links became more balanced and less strongly biased towards the baseline gender category.

In experiment 3, the authors asked whether participants would also revise their descriptions of their own personality. Using the Bem Sex-Role Inventory @bem1974measurement, participants assessed themselves on characteristics including gentleness, competitiveness, and sympathy. The more strongly they experienced ownership of the other body, the more they attributed to themselves characteristics conventionally assigned to the other gender.

The third experiment makes the problem particularly clear. Changes in the body perceived as one's own were associated with changes in the personality attributed to oneself. Bodily form and personality are distinct attributes: perceiving a different body does not logically entail having a different personality. The extension of a bodily illusion into personality attribution therefore calls for an account of what connects these representations.

Social gender norms offer a plausible connection. Consider someone who does not regard themself as competitive, but has learned to associate a male body with competitiveness. If this person comes to perceive their body as more male, the learned association brings their bodily perception into conflict with their existing self-description. The prediction error arises because society has taught them to expect these otherwise distinct characteristics to go together.

On this interpretation, the inference from a bodily change to a personality change depends on an expectation connecting a bodily feature with a personality trait. I suggest that culturally acquired gender stereotypes supply this expectation. The experiment is consistent with this explanation, but does not independently isolate the cultural origin of the association or establish that it is the only mechanism involved. It provides a reason to investigate how social gender norms connect bodily representation with the wider self-concept.

This interpretation fits the "Thinking Through Other Minds" (TTOM) model of #textcite(<Veissi_re_2019>). Through participation in recurring cultural practices, we come to understand the expectations, behavioral patterns, and shared norms of others. These acquired expectations guide our attention and actions. Consequently, by inferring the "priors" held by others, we effectively "outsource" a significant portion of our cognitive activity. Expectations linking physical appearance to personality traits can serve as one such culturally acquired prior.


The same question can also be approached through sound. #textcite(<Clausen2021Action>) designed a system that altered the frequency of participants' footsteps in real time. Participants wore instrumented sandals. Microphones attached to the sandals captured impact sounds, which were amplified and equalised, then replayed through isolating headphones that blocked unprocessed sound. Two extreme conditions were used: high-frequency amplification, making footsteps sound lighter and more stereotypically feminine, and low-frequency amplification, making them sound heavier and more stereotypically masculine.

In the female group, the high-frequency condition increased self-reported lightness and femininity and reduced perceived strength. It also increased reported closeness to the female in-group on the Inclusion of Other in the Self measure @aron1992inclusion. However, IAT scores in this group did not change significantly.

In the male group, a partial mirror pattern appeared. After high-frequency footsteps, men also reported increased femininity. More notably, their IAT scores shifted significantly toward stronger implicit self-female association than baseline and low-frequency conditions.

When both groups were analysed jointly, footstep frequency significantly affected subjective ratings of body weight, masculinity-femininity, strength, and IAT scores. This supports the conclusion that auditory input alone, without visual or VR manipulation, can induce a small but measurable shift in measures of gendered self-perception.

These studies bring us back to the social content of gender identity. They show that some measures of gendered self-perception respond to altered bodily information. They do not directly establish the developmental origin of gender identity as a whole, and a change in masculinity-femininity ratings or implicit association is not equivalent to a lasting change in identity. PP and TTOM provide a possible account of how learned associations mediate these effects. Their role here is to explain how socially acquired content could become pre-reflective, rather than to prove the conceptual dependence established in the previous section. I now turn to the structure of these associations and their implications for gender abolition.

= Gender Abolition

Informed by the aforementioned studies, I propose the following model: gender can be treated as a social-norm system that links ontologically distinct attributes. By "distinct," I mean that possessing one attribute does not, by itself, determine the meaning or appropriate value of another. This does not require every trait to be statistically independent or deny biological relationships among bodily features. The problem is the use of gender to organise heterogeneous characteristics into expectations about what a person is or should be.

In a given setting, gender categories may be associated with particular bodily features, forms of dress, colours, activities, occupations, and personality traits. Familiar stereotypes connect woman/girl/female with developed breasts, pink, housework, dolls, dresses, jewellery, make-up, quietness, and baby-caring; they connect man/boy/male with beards, blue, computers, toy cars, suits, ties, competitiveness, and extroversion. These are examples of associations that may be learned in particular settings, not definitions of women and men or claims that these associations are universal.

Here it is necessary to distinguish "gender associations" from "gender stereotypes." I use the former for learned connections that give a feature, practice, or relationship a gendered meaning. Stereotypes are a more specific case, in which attributes are generalised across a category or treated as appropriate for its members. Rejecting explicit prescriptions, such as "women should be quiet," does not necessarily remove an automatic expectation linking women with quietness. However, the bare fact that a category has social meaning does not establish that it contains such a stereotype. My argument concerns the learned associations through which categories organise embodied self-perception, including those that continue to operate after explicit prescriptions have been rejected.

Through TTOM-like cultural learning, beginning in childhood, we can internalise expectations about how others understand us and use them to infer self-identity and organise behaviour. A combination that conflicts with these expectations may generate prediction errors, making revision of one's self-model or behaviour one possible response. Since anatomy is only one feature among them, the resulting identity need not align with one's birth-assigned sex. The process is not deterministic: a person can also question the expectation, reinterpret the category, or change their social environment.

The further possibility is a feedback loop. A socially shared category allows people to learn what its members are expected to be like, predict how others will recognise them, and interpret their own characteristics through those expectations. Someone who initially only partly fits the category may consequently come to describe themself, act, or perceive their body in ways that fit it more closely. As these changes become visible to others, they can strengthen the shared representation from which the expectations were learned. The category would then help reproduce the combinations it appears merely to describe.

This is what I mean by a possible cognitive attractor. The name alone does not produce the effect; it must be embedded in shared practices and expectations. Conversely, a socially salient pattern can enter this process without a single dedicated word. Naming matters insofar as it makes a combination easier to communicate, recognise, and repeatedly use as a common model. My concern is therefore the unequal capacity of combinations to enter and sustain this recursive process, rather than the mere possession of a dedicated word.

This feedback mechanism is a theoretical extension of the evidence, not a longitudinal result demonstrated by the body-ownership or footstep experiments. It predicts that, where category-based expectations are repeatedly reinforced, greater exposure and participation may lead some initially less typical members towards the category's locally salient traits. Testing this would require distinguishing changes within individuals from the selection of already similar people into a category, and examining whether the effect varies with the strength of local associations. The possibility of updating the category rather than conforming to it is also part of what such research would need to examine.

This model points to a form of "gender-centrism" that cannot be reduced to androcentrism, heterocentrism, or cisgender-centrism. It establishes gender as a central category for understanding the world and ourselves, making particular combinations more readily available as models of a person. An extroverted person with a penis, who likes wearing dresses, playing with dolls and toy cars, programming, and raising babies, can of course be described. The difficulty is that this combination may have less support as a shared model through which people form and sustain their self-understanding. Gender abolition, as I understand it, aims to remove the expectation that these characteristics need to form a recognisable gendered whole.

If the problem lies in these associations, an apparent solution is to loosen them and multiply the identities available @Cull2024What. However, can this remove the asymmetry while preserving gender identity in its contemporary pre-reflective form?

= So, what about gender identity?

One may say: "absolutely! We should abolish gender stereotypes, therefore all different kinds of gender identity can be expressed freely!" Many people believe that we can abolish gender stereotypes while protecting gender identity, and that creating more identities can include more diverse experiences. #textcite(<Cull2024What>) develops a proposal for gender pluralism. My objection concerns what multiplying categories can accomplish, and which sense of "abolishing stereotypes" is compatible with preserving them.

The argument has two distinct steps. First, as I argued from the definitions, gender identity requires meaningful gender content. Second, on the neurocognitive account proposed here, contemporary pre-reflective gender identity is sustained by learned associations through which bodily experience and other features of the self acquire gendered significance. The first step does not by itself prove the second. Nor does either step require every person to endorse the same stereotypes. The conclusion is conditional: if these associations supply the content through which the relevant self-model operates, completely removing them also removes the basis for reproducing that form of identity.

Consider "yhutabikoper," an arbitrary word I created by pressing the keyboard randomly. Someone could adopt it as an identity, and a group could decide that it names everyone who chooses it. Nothing makes this logically impossible. However, the act of adopting the word does not by itself explain a distinctive, embodied sense of being yhutabikoper. For that, the proposed model requires learned expectations connecting the category with experience. If membership acquires shared practices, bodily cues, or patterns of recognition, those associations supply content that the initially empty word lacked.

A critic might therefore propose a minimal gender category based only on historical membership, social relations, or mutual recognition. Such a category need not contain familiar stereotypes about personality, clothing, or occupations. I accept that possibility. The further question is whether it preserves the psychological phenomenon examined here. A historical label or voluntarily adopted affiliation can survive even if gender no longer organises everyday bodily and social expectations. In that setting, gender identification might take the form of a minority subculture or historical role-play. These practices can be serious and valuable without reproducing the contemporary role of gender in ordinary self-perception.

This distinction is not absolute. A voluntary affiliation can become habitual and pre-reflective through repeated participation. If a gender subculture developed that way, it would have established its own learned associations; it would not be a case of the same phenomenon surviving the removal of all such associations. Gender abolition need not prohibit these affiliations. The political question is whether their conventions again become general expectations through which people's bodies, personalities, and activities are organised, including those of people who have not chosen to participate.

The disappearance at issue is therefore not the logical impossibility of using a gender word. If the associations that sustain the current self-model cease to be transmitted, that model would, on this account, lose its basis for cultural reproduction. People who have already acquired those associations would not instantly lose them. The claim concerns the formation of future selves as well as the persistence of present ones, and should not be confused with a prediction that existing identities vanish as soon as an institution changes its vocabulary.

If "abolishing stereotypes" means removing rigid prescriptions and hostile generalisations, its compatibility with retaining gender identity remains open. If it means removing all the learned gender associations that sustain the pre-reflective identity examined here, the proposed model gives a reason to expect that identity to change or cease to be reproduced. My objection is to treating these two projects as interchangeable. A defender of minimal gender must explain which content remains and what psychological and social work it continues to do.

The second problem concerns the strategy of multiplying labels. Gender labels can encompass extremely heterogeneous contents: bodily features, personality, clothing style, game type, toy type, division of labour, occupation, behaviour, aesthetics ... A simple calculation illustrates the scale of the space being organised. Suppose, solely for this illustration, that we code bodily variation along one dimension with five values, three further dimensions with three values each, and twenty-two additional attributes as present or absent. These are stipulated coding choices, not a claim that anatomy naturally divides into five types, that personality is ternary, or that every combination is biologically realisable.

The number of combinations in this simplified space is:
$ 5 dot 3 dot 3 dot 3 dot sum_(i=0)^22 C_22^i = 135 times 4,194,304 = 566,231,040 $

The calculation illustrates how quickly a combinatorial space grows; it does not count the genders that exist or the labels anyone is committed to creating. Treating every point as a separately learned, socially shared identity would exceed plausible human vocabulary capacities @Brysbaert2016Many@Collins2023English. However, a pluralist need not propose one label per combination. People can describe themselves through combinations of ordinary words, and a single category can include many different people. Neither of these possibilities is refuted by the number.

The reason the calculation matters to my argument lies in the TTOM mechanism. Some combinations become familiar shared models around which expectations, practices, and self-descriptions accumulate. Others remain describable without receiving comparable support in that process. Where the proposed feedback loop operates, the former have a route to attracting further instances and reproducing themselves that the latter do not possess to the same degree. Compositional language solves the problem of describing an individual; it does not by itself give every description an equal role in shaping future individuals. Equally, if a description does acquire that role without a dedicated label, it belongs on the socially shared side of the distinction.

This is the "cognitive inequality" I am concerned with. It is an asymmetry in the opportunities for different combinations to become socially supported forms of self-understanding. It is not automatically an injustice merely because some words are more familiar than others. The additional normative premise is that people should be able to develop and combine their characteristics without some gendered packages receiving systematic support that makes alternatives harder to inhabit. Where shared categories direct self-models towards those packages, the asymmetry matters to that freedom. Its importance depends on the strength and consequences of the feedback, rather than following from the existence of a label alone.

Multiplying categories can make previously marginalised experiences more intelligible and reduce the authority of the binary. My objection is that this achievement does not, by itself, remove the mechanism. A finite set of shared models may become more inclusive while retaining differences in which combinations receive recognition, reinforcement, and opportunities for reproduction. The combinatorial argument helps explain why indefinitely adding microlabels is an incomplete answer to this problem. TTOM supplies the proposed causal connection; the commitment to freedom from gendered expectations supplies the reason for objecting to it.

Some might argue that new gender labels need not have a fixed value for every dimension, but can be internally diverse concepts based on family resemblance. This is a serious alternative. Family resemblance removes the need for a rigid checklist, but it does not establish that all members are equally available as models of the category. Where some exemplars or clusters are more salient, people may still learn expectations around them and move towards them. Whether this happens, and to what extent, is a question about the practices sustaining the category. A genuinely open category that avoids such convergence would weaken this part of my criticism; its existence cannot be ruled out by arithmetic.

My description of a linguistic "enclosure movement" should be understood in this limited sense: selected regions of the space of possible characteristics can acquire a shared name, social support, and a capacity to reproduce themselves. The issue is not that every boundary is fixed or every identity oppressive. It is that increasing the number of recognised regions does not necessarily remove their unequal influence on how people develop. Gender pluralism therefore needs an account of how its categories avoid or sufficiently reduce this effect, rather than an assumption that proliferation alone resolves it.

The difficulty of removing this asymmetry is one objection to gender pluralism. A different objection to abolition concerns what people already value: even if gender categories impose these limits, does the pleasure and sense of self they provide justify preserving them?

= "But many people love it!": Value and Transition

In an interview with #textcite(<Williams2014Gender>), Butler emphasises the pleasure that people find in their genders and the importance of gender to their sense of self. #textcite(<Cull2019Against>) likewise objects to abolition in terms of its consequences for transgender people and the recognition of their identities. These concerns should not be reduced to a casual preference for familiar labels. Identity, belonging, and continuity of self-understanding can have real value, and losing their social support can be a real harm.

Two claims must nevertheless be distinguished. The first is that the disappearance of a category is itself the disappearance of the people currently described by it. The second is that changing the institutions and relationships that sustain a category may harm those people. The first does not follow from the meaning of abolition. People can retain their bodies, memories, relationships, and needs even if a classification ceases to organise social life. However, this does not refute the second claim. A future society without the category cannot, merely by being imaginable, establish that getting there would be harmless.

The cis/trans distinction illustrates the conceptual point. Under a definition based on the relation between gender identity and birth assignment, a society that never instituted such assignments would lack one of the terms needed for that comparison. This thought experiment shows how the application of a category depends on social conditions. It does not show that stopping official birth assignment today would immediately abolish informal classification, erase anyone's history, or remove their need for recognition. Still less does it establish that Butler or Cull must regard transgender status as immutable or transhistorical in order to raise a concern about existing people.

I do not shy away from the possible cost. On the model defended here, a society that ceased to reproduce gender as a general structure of self-understanding would also cease to reproduce cisgender and transgender identities in their contemporary form. Some things that people now value might be lost in that transition. The relevant question is whether those losses are decisive reasons to preserve the social conditions that generate them. "Someone finds meaning in it" provides a reason to consider that person's interests; it is not a sufficient condition for preserving the institution indefinitely.

For example, a person can find genuine meaning in a gendered division of labour without that meaning settling whether the division should organise the lives of future people. This does not make their attachment false or worthless. It distinguishes the value an existing person derives from a practice from the justification for continuing to reproduce that practice. The same distinction applies to gender identity, even when its value is more intimate and deeply embodied than a consciously chosen social role.

The comparison must therefore include the costs of preservation. On my account, preserving the associations that sustain contemporary gender identity may also preserve shared expectations that channel otherwise diverse combinations towards recognisable models. Those expectations affect people who value their gender and people who find themselves difficult to understand within the available categories. The normative premise of my abolitionism is that freedom from this general organisation of human characteristics should take priority over the indefinite reproduction of the identities it supports. This is a political judgement informed by the proposed mechanism, not a conclusion that can be read directly from neuroscience or definitions.

There is also a difference between an existing person losing support for an already formed identity and a future person developing without that identity. On the proposed model, someone who grows up without the relevant gender associations would not first acquire the contemporary self-model and then be deprived of it. This does not prove that their life would be better or that gendered forms of pleasure have no value. It means that the losses experienced by presently socialised people cannot simply be projected onto everyone who might live in a different social order. The comparison must consider what other forms of self-understanding, association, and pleasure could develop there.

This is not an elimination of contemporary transgender people, nor does it mean that their healthcare is unnecessary. My argument begins from an acknowledgement of the suffering of contemporary transgender people, including myself. Social classifications and the expectations attached to them are central targets of my criticism, but the account given here does not establish that every form of bodily distress has a wholly social cause or would disappear with gender. Bodily preferences and needs must be addressed on their own terms; their legitimacy does not depend on the permanent existence of the categories now used to describe them.

The distinction also matters for transition. A commitment to ending the reproduction of a social structure does not justify every measure presented in its name. Withdrawing healthcare, coercively denying people's self-descriptions, or abruptly removing the support on which they depend would require arguments that the imagined endpoint cannot supply. A defensible transition should reduce compulsory gender classification and the expectations attached to it while supporting people whose lives have already been shaped by those conditions. Historical affiliations, communities, and voluntary practices need not be prohibited for gender to cease to serve as a general organising principle. These are constraints on the political project, not a complete institutional programme or a guarantee that no one will experience loss.

This is not because I hate gender identity and want to destroy it. In fact, I really, really enjoy my gender identity and gender euphoria. My point is that the value I find in an identity does not, by itself, give me a reason to require the indefinite reproduction of the social conditions that make it possible. If maintaining contemporary pre-reflective gender identity requires continuing the associations through which human characteristics are organised into gendered combinations, I favour abolishing that general structure even at the cost of losing something I value. I believe the latter is entirely worth the cost. My willingness to bear that loss does not settle what can be asked of others, but it makes clear that my argument does not depend on denying that the loss is real.

I therefore defend gender abolition as a systematic response to the problem identified here. It addresses the reproduction of the classificatory structure itself, rather than relying solely on making more positions available within it. The evidence does not establish it as the only possible response. A competing project might retain minimal, voluntary associations while preventing them from organising other people's lives. The disagreement then concerns whether that separation can be sustained and whether its remaining costs are justified by the value it preserves.

= Conclusion

This article has developed an argument for gender abolition by separating conceptual dependence, neurocognitive explanation, and political justification. An identity defined through social gender categories requires access to their meaning; in that specific sense, its content cannot be innate independently of social acquisition. PP and TTOM offer an account of how learned content can become an immediate, pre-reflective sense of self. The experimental studies support the responsiveness of some gender-related self-representations to bodily information, while the wider account of category reproduction remains a theoretical proposal that requires further testing.

The central difficulty for gender pluralism is not that language cannot describe every possible person. It is that shared categories may acquire an unequal capacity to shape the people they classify. Through recursive cultural learning, expectations can influence self-models and behaviour, thereby reinforcing some of the combinations from which those expectations were learned. Multiplying labels can expand recognition without necessarily removing this process. The combinatorial illustration clarifies the limits of treating proliferation as an exhaustive solution; it does not prove that every possible form of pluralism must fail.

The argument also distinguishes preserving a gender word from preserving contemporary pre-reflective gender identity. Historical categories and voluntary affiliations could survive a society's abandonment of gender as a general organising principle. They might even develop local, habitual forms of identification. What cannot be assumed, on the account proposed here, is that the same embodied self-model will continue to be reproduced after the associations sustaining it have all been removed. A proposal to abolish stereotypes while retaining gender identity must therefore specify what is being abolished, what content remains, and how that content operates.

I favour a society in which bodily features, personality, dress, activities, and relationships can be understood without being assembled into gendered packages. This does not require denying biological relationships among traits, abolishing historical knowledge, or prohibiting people from forming communities. It requires questioning why gender should continue to organise these characteristics and the expectations attached to them. Describing relevant bodily features directly, rather than treating a gender label as their proxy, is consistent with that aim.

The fact that people value their current identities remains a serious consideration. I have argued that it does not, by itself, justify reproducing the structures that sustain those identities indefinitely. Gender abolition may involve real losses, and defending it requires both a comparison with the costs of preservation and attention to the people who bear the costs of transition. I believe the freedom it seeks is worth pursuing, while recognising that this judgement depends on normative commitments as well as the proposed account of gendered cognition.

Even readers who reject that political conclusion may find the framework useful for understanding gender identity without treating it as a socially independent inner essence. For transgender individuals who, like myself, understand their experiences through material reality and personal history, social acquisition need not make those experiences less real. An experience can be learned, embodied, deeply valued, and deserving of care without the conditions that reproduce it being beyond political criticism. It is this distinction that makes both respect for contemporary people and an argument for a different future possible.

#bibliography("references.bib", style: "chicago-author-date")
