#import "../lib.typ": *

In this section, I will demonstrate that the idea of an "innate," or "inherent" gender identity is groundless and directly contradicts many biological laws. Multiple theories, especially ones about "male/female brain" and body representation, fail to explain "gender identity" satisfactorily. Finally, I will establish the predictive coding theory as the biological mechanism of gender identity.

#textcite(<APA2015Guidelines>, <NHS2022Gender>) define "gender identity" as "inherent" or "innate" sense, which is untenable because  "gender" is a social construct @Waylen2013Oxford. Gender construct can change very fast @Robb2018Becoming@Paoletti2012Pink. Using many genes to encode such a changeable abstract concept is biologically inefficient and impractical. Also, this claim is too _ad hoc_ because similar phenomena (cultures being pre-coded in genome) are not found elsewhere. In contrast, evolving a brain with high neuroplasticity to learn abstract concepts is far more reasonable.

// As an analogy, infants have the sucking reflex without knowing what a "breast" is. Innately encoding a "gender identity" is more useless than encoding a "breast." The latter would allow infants to recognise breasts innately, distinguish what should and should not suck, and avoid sucking on harmful things. Therefore, an innate "gender identity" is less probable than an innate concept of breasts. 

// By definition, it clearly falls under the concept of "narrative identity" or "narrative self", specifically, "self-concept," which is defined as the "conscious beliefs about the self that are descriptive or evaluative" @Fanti2024Dual. In contemporary psychology, cognitive science and philosophy of mind, there is a broad consensus that narrative identity is essentially a posteriori. It is formed through the integration and interpretation of personal life experiences and is deeply influenced by sociocultural frameworks @Fanti2024Dual. Therefore, claiming that gender identity is a priori or innate creates a profound philosophical contradiction.

// Primatologist Frans de Waal claimed that "primates are born with a gender identity" because their behaviour does not align with the statistical type for their phenotypic sex, such as the phenotypically female chimpanzee Donna, who occupies territory and fights with others @DeWaal2022Different@Morin2022Frans. However, nobody has ever asked "Hi, Donna, what is your gender identity?" De Waal's claim is effectively saying that gender identity is a behavioural characteristic of animals. Equating "aggression" with "male identity" is not only anthropomorphism, but also a logical leap. This is a sexual dimorphic behaviour characteristic; its relationship with "gender identity" is unjustified. 

Many neuroscience studies claiming an "innate gender identity" involve circular reasoning. They used the brains of so-called "cisgender" individuals as the standards of "male brains"/"female brains." However, these studies did not explain the causal relationship between the brain structure and gender identity. Without human society and culture, this would just be a sexual dimorphic neurological trait, but not "male" or "female." If it could be considered "male brain" or "female brain," tallness or shortness would also be considered "male height" and "female height," because they are also sexual dimorphic characteristics @Wells2007Sexual. This is a precious repeat of the aforementioned fallacies about "sex." Additionally, research shows that almost no one's brain is entirely "male" or entirely "female"; the vast majority of people have a mixture of characteristics @Baxendale2025Brain@Joel2015Sex@Zabalegui2024After.

Some transgender individuals report that they have a discomfort with their body characteristics from an early age. #textcite(<Case2017Altered>, <Lin2014Neural>, <Ramachandran2008Phantom>) reveal that this is indeed from internal body representation incongruence. This model overcomes the brain sex model by establishing a clear causal relationship between brain structure and psychological phenomenon. However, according to the sex/gender division, a preference for a specific body morphology should be considered a "(phenotypic) sex identity" or "body identity" rather than a "gender identity." This is a category error. Furthermore, the reason they are interpreted within the framework of "gender" is a product of the questionable definition of phenotypic sex. Why is a short "woman" who wants to be taller not considered transgender?

A nature-nurture co-operation hypothesis is strongly supported by the aforementioned neurological studies. #textcite(<Case2017Altered>) suggest an innate multimodal body representation but acknowledge that culture and experience can shape it, making the "innate" vs. "acquired" line blurry. #textcite(<Lin2014Neural>) reveal that transgender individuals' brains show high connectivity between the body representation areas and visual/auditory processing areas. They suggest this means transgender individuals are "integrating massive visual and auditory cues to shape their body image," and transgender people's "distinct neural network of body representation can be coterminal to genetic constitution, developmental factors and learned experience in their life." In other words, our brains use learned socio-cultural knowledge to interpret a vague, underlying discomfort into a specific, socially coherent narrative. Nonetheless, these studies, as well as similar neurological studies, mainly focus on "typical," "early-onset" transgender individuals. In contrast, studies focusing on "atypical" transgender or non-binary individuals are relatively rare @Zabalegui2024After. #textcite(<Langer2023Examining>) establish that only about 50% of transgender individuals in their study report the body phantom experience. #textcite(<Bonazzi2025Gender>) demonstrate the significant relevance between autism and transgender identity. The neurological heterogeneity between body representation incongruence and autism implies that "transgender" people do not share a biological essence.

According to the predictive coding framework, the human brain functions as a continuous prediction engine, leveraging past knowledge and internal models to efficiently anticipate sensory data and thereby minimise unexpected outcomes @Clark2013Whatever. It provides a novel model to understand the aforementioned nature-nurture co-operation. #textcite(<Tacikowski2020Fluidity>) demonstrated that the perceptual illusion of owning a phenotypic opposite-sex body causes a dynamic, robust, and automatic shift in gender identity, characterised by a more balanced subjective identification with both genders, updated implicit self-associations, and reduced gender-stereotypical beliefs regarding one's own personality. If an individual has a sensory processing variation (e.g., the breast feels "alien"), this creates a prediction error. The brain can resolve this error by updating its "self-model." If the social environment offers a category ("Transgender Man") that explains this feeling, the brain adopts this identity to minimise the predictive error. Similarly, as demonstrated by #textcite(<Clausen2021Action>), footstep sounds can modulate gender identity and the sense of self-group relation in cisgender participants.

Therefore, "gender identity" is shaped through updating our self-model to resolve the continuous prediction error in multiple aspects because one or many of our embodied raw feelings are incongruence with the gender categories assigned to us. Body representation incongruent people's raw feeling might be "this body part isn't mine." Autistic people's raw feeling might be "the arbitrary gender norm is hard to conform and makes me uncomfortable" (sensory overload). Some people with gender non-conforming personalities and behaviours might feel "I dislike the personality/temperament externally forced on me." Other transgender individuals might develop their gender identity through other routes in their personal history. The gender construct ties disparate causes together and make us interpret them as "This means I am a girl/boy/man/woman/non-binary person." "Gender identity" is therefore not an internal essence, but a constructed self-model. It is a chimaera that connects pre-linguistic embodied raw feelings with a socially constructed category of identity. Then it claims this connection is "natural," using the raw feeling to legitimise a social construct.

 Being analogous to deep learning (connectionism), gender construct is a training set that contains two classes: Class 0 (female) is consisted of feminine faces, vaginas, clitorises, developed breasts, pink, purple, brooms, mops, kitchens, dolls, stuffed toys, dresses, Mary Jane shoes, jewellery, make-up ... On the contrary, class 1 (male) is made up of masculine faces, penises, testicles, undeveloped breasts, Adam's apples, beards, blue, computers, documents, architecture, toy cars, pants, suits, ties ... An individual's gender identity is the product of it. The root cause of the suffering and oppression is the social construct about gender that continuously creates prediction errors. Transgender status is not an individual condition stemming from an "inner self" that requires medical care #footnote[I fully acknowledge that body representation incongruence is an internal body condition requiring medical treatment. However, as we previously argued, considering it "gender identity" is either begging the question or a category error. ], but a serious political threat to our very existence.

It is very simple and elegant, providing distinct advantages. We successfully removed two redundant, unnecessary entities, "sex" and "gender identity," and provide better explanatory power. In this model, the term "gender" has a consistent meaning in "gender construct" and "gender identity." It successfully answers the question "what _gender_ means in _gender identity_" by connecting neurological states with external gender construct, and avoids fallacies like begging the question or the category error exhibited in other models. Moreover, we regard the phenotypic sex also as a specific gender stereotype, therefore perfectly incorporates the body representation incongruence into this theory. 
I'm not saying that what "phenotypical sex" refers to is socially constructed. It certainly isn't; it's a part of our real, biological bodies. What I mean is that the scope of this concept is socially constructed.
It does not deny this pre-language neurological pain, but other points out that our naming and classification of it is shaped by social culture. It elegantly answers the question "why is body representation incongruence about this part 'transgender', but body representation incongruence about another part is considered 'body integrity identity disorder'." Therefore, when TERFs say "you are just conforming to gender stereotypes," we can immediately respond: "Yes, I know I am. But you don't know that you are also conforming to gender stereotypes when you advocate the so-called 'sex' (phenotypic sex)." 

// Therefore, we must distinguish between the biological causes and the psychological explanation. The former are continuous, mosaic, and low-level biological traits. The latter is a discrete, high-level semantic label recruited by the brain's predictive machinery to make sense of the former within a specific cultural framework. Confusing them is the fundamental error of gender essentialism.