#import "../lib.typ": *

// %I posted my initial viewpoint on three different platforms. 

// % I told them, "This is not queer. The difference between queer theory and my viewpoint is like the difference between Giordano Bruno's pantheistic philosophy and the Hubble model of the universe. They are within two completely different disciplines and frameworks. This is also not a reinvention. You can't say that Hubble reinvented Bruno's pantheism." #footnote{This is a fact. I started thinking entirely based on the first principles of evolutionary biology. I read _Gender Trouble_ after I completed my introspection.} 

// %Later, with the goal of so-called "community solidarity," I wanted to participate in a more moderate way, no longer mentioning that "gender is an oppressive concept," "we should completely abolish gender." I still couldn't understand why, after sharing an article about the lack of inclusivity of ASAB for intersex people in one community, I was immediately banned. Another community accused me of "gender essentialism" for thinking that "phenotypic sex is more accurate and inclusive than ASAB." I don't believe "phenotypic sex" is a real thing at all (as we discussed earlier). It is a proxy, like ASAB, to represent the gender socialisation patterns. If "phenotypic sex" is more accurate, then of course we should use it. A more precise representation means higher inclusivity, recognising a richer biological and sociological diversity. As a man-made scientific model, what does it have to do with "essentialism"? I don't believe there is a metaphysical essence or a Platonic Form of "male" and "female" behind this model. I never discussed the metaphysical status of this concept at all. This viewpoint is moderate and morally necessary. I am curious if they really believe that the person in the thought experiment is a "cisgender female." If they had seriously read my post, they could not have reached this conclusion. It completely violates their own values.
// %
// %

When I started exploring my gender identity, I kept encountering intellectual barriers, I posted my questions on some platforms, including Reddit, RedNote (Xiaohongshu) and Zhihu (a Chinese Q&A website), hoping for some advice or help. However, almost no one responded to me seriously. I was insulted or degraded on all three platforms, and my account was banned on Reddit. These communities completely refuse to understand what others say and explain their own views.

// Except for the aforementioned insults and banning, I received some more subtle forms of violence. They asked me, "Isn't this just queer?" or "You've reinvented queer theory."#footnote[When they interpreted my points as "reinventing queer theory," they did what Derrida spent his whole life opposing: eliminating the abosolute alterity of the Other, reducing them to a part of themselves.] Some others said that my viewpoint was "solipsism" or "Landian Accelerationism," which I completely failed to understand.#footnote[Ironically, queer theory is more like "gender accelerationism" to me. Both left-wing accelerationism and Land's right-wing accelerationism are theories about "pushing the inherent logic of capitalism to its limits, leading to its self-destruction and creating a new world." The difference lies in the "new world" they envision (socialism/anti-humanism). They and queer theory are all about resisting a system by repeating/accelerating its own mechanism. ] Moreover, they responded to my analysis of "Indo-European-centrism in gendered pronouns" @Sun2025GenderAbolition with the personal attack, "Your mum is also a form of cultural invasion."

// It took me a long time to understand that their standard of "inclusivity" seems to be whether it sounds comfortable to them, and their standard of "comfort" seems to be arbitrary and without any fixed logic. The inclusivity I understand is using more accurate scientific models to represent human biological and sociological diversity. Suppose a model can describe and distinguish more diversity (e.g., different types of intersex people), it is more precise and more inclusive than a model that flattens or ignores these situations (like "assigned sex at birth", as discussed in #plaincite(<Sun2025GenderAbolition>)).

The prerequisite for any dialogue is that both parties are equal, mutually respectful, willing to listen, engage with the opponent's actual arguments, and willing to modify their own positions based on logic and empirical evidence. They don't care what "gender essentialism", "accelerationism" or "solipsism" really are. They are not academic philosophical classifications, but the ultimate political tool like "blasphemy" or "witchcraft," which an ideological system uses when facing a challenge it cannot respond to.

// #footnote[
// "Thus, the attempt to preserve genealogical historiography from a relativist self-denial by means of its own tools falls short. In becoming aware of its own provenance from this alliance of scholarly and disqualified knowledge, genealogy only confirms that the validity claims of counterdiscourses count no more and no less than those of the discourses in power  --  they, too, are nothing else than the effects of power they unleash. Foucault sees this dilemma, but once again he evades any response.

// "Foucault cannot adequately deal with the persistent problems that come up in connection with an interpretative approach to the object domain, a self-referential denial of universal validity claims, and a normative justification for critique.

// "If one admits only the model of empowerment, the socialization of succeeding generations can also be presented only in the image of wily confrontation. Then, however, the socialization of subjects capable of speech and action cannot be simultaneously conceived as individuation, ... both theories lack a mechanism for social integration such as language, with its interlacing of the performative attitudes of speakers and hearers, which could explain the individuating effects of socialization."]
This reminds me of #posscite(<Habermas1987Philosophical>) criticism 
of Michel Foucault. He argued that Foucault's reduction of everything to "power" made rational communication impossible and destroyed the foundation for building a truly free society based on communicative rationality. This is perfectly shown in the communities deeply influenced by post-structuralism. Foucault has taught them that every communication is just a power operation. When you tell people that there is no truth, only "regimes of truth"; no reason, only "power/knowledge"; no living author, only the "author function"; no common, universal human destiny, only various discourses fighting each other -- what do you expect them to do? If someone presents a challenging argument, you have no obligation to listen to its reasoning; you only need to analyse its "discursive effect" #footnote[In my case, it was not even a real discursive effect, but their own prediction of a possible discursive effect.] and see it as an "operation of power."

// %According to this logic, Foucault himself should be the first to be judged, because "morally judging and punishing an author based on discursive effects" is precisely the real discursive effect produced in the discourse network by Foucault as an author function. Although this was not his own intention, its discursive effects have caused exclusion and harm in the real world. Foucault is the only author who cannot claim "that's not what I meant," because he himself (as the author function) has forbidden himself (as a natural person) from doing so.

The greatest strength of Habermas's critique is its immediacy and structurality. Habermas's critique was fully articulated before Foucault's theory was "vulgarised" by the followers we see today. It did not need to wait for any subsequent events for verification, because it targeted the inherent structure. If Foucault was still using academic language, making arguments, writing, and expecting to be understood, he was inevitably caught in this contradiction. It is somewhat ironic that Foucault, when interviewed by #textcite(<Boesers1977Folter>), appealed to his intent to defend himself; he claimed that the French _raison_ is different from the German _Vernunft_, _raison_ is instrumental rationality, _Vernunft_ also includes value rationality. In this event, the natural person Foucault "resurrected" the "dead" author-function Foucault to practice Habermas's communicative rationality, trying to use rational argument to make others understand, he was not destroying reason. This demonstrated that it is not just a "vulgarisation" that has occurred in a few specific communities. It is the inevitable result of his theory that even Foucault himself cannot avoid. // Because his world is inhabitable.

Out of the principle of communicative rationality, I accept Foucault's own defence about his original intent. I completely acknowledge that Foucault's original intention is providing an analytic framework rather than morally judging and punishing an author based on discursive effects. However, analysing it with #posscite(<Foucault1972Archaeology>) own theory: 
// #footnote[
//     "In the nineteenth century, psychiatric discourse is characterized not by privileged objects, but by the way in which it forms objects that are in fact highly dispersed. This formation is made possible by a group of relations established between authorities of emergence, delimitation, and specification. One might say, then, that a discursive formation is defined (as far as its objects are concerned, at least) if one can establish such a group; if one can show how any particular object of discourse finds in it its place and law of emergence; if one can show that it may give birth simultaneously or successively to mutually exclusive objects, without having to modify itself."
// ]
Foucault's description of the world as an anonymous, impersonal discursive field, claiming that the author's own intention is not important, is not just descriptive but also productive. His works, through discursive effects, "reproduced" this impersonal discourse operation, providing people with a powerful new discourse and new arguments as intellectual weapons, allowing them to ignore the author's intent, refuse good-faithed interpretation, and dismiss demands for intellectual coherence and logical self-consistency as "discipline," "instrumental rationality" or "governmentality." Like the Enlightenment rational discourse produced the Cartesian rational subjects and medical discourse produced homosexuals, Foucault's theory also produced a specific type of subjects that does not care about the intentions of others and refuses rational communication. Foucault should have foreseen this consequence using his own theory.

Everything the dogmatic and exclusionary transgender communities have done, academic post-structuralists have also done, just packaged it in complex philosophical theories. #textcite(<Butler1990Gender>) used straw man fallacy and Texas sharpshooter fallacy when criticising #posscite(<Page1987Sex>) study @Sun2026Aristotelian. What post-structuralists did to Rebecca Tuvel in the _Hypatia_ transracialism affair is also a typical case. #footnote[Both gender and race are classification systems based on morphology and now falsified by genetics. They are both assigned many stereotypes. So theoretically, race can also create prediction errors in brains of individuals who do not comfort the racial stereotypes, therefore forming trans-racial identities.]

This issue is not only intellectual, but also ethical and political, having caused real exclusion and violence. When someone raises a logical query about "gender identity," it is not seen as an intellectual act of truth-seeking. It is interpreted as a political act, a form of discursive violence. Let us analyse it with their own theory again: the claim that "asking 'isn't "trans women are women" a tautology' is a discursive violence and epistemological hegemony; it harms transgender people" is not an objective description of the psychological status of all transgender individuals, but a reproductive and performative assertion that implies a prototype for "transgender people": you must be harmed by this question, you must value subjective feeling over objective truth and logical consistency, otherwise you're not "real" transgender. It is a real discursive violence and epistemological hegemony that excludes transgender individuals who are from the scientific community or the analytic tradition, asserting that they are a deviation from the "standard" transgender status.

Rational dialogue is valuable because: if critics are well-intentioned, dialogue fosters mutual understanding. If they are malicious, dialogue exposes their unreasonableness to others and helps those who have misunderstanding, especially transgender individuals during their self-exploration. For example, the similarity between my question and TERFs' criticisms about tautology shows that this is a real, standpoint-independent logical question. Although they might raise this question maliciously, it may still expose some real, response-worthy logical issues. Answering it with clear arguments will help other people, including some transgender individuals. When this crude cancellation becomes an unreflected, unconditioned response, those who ask questions in good faith, including some transgender people themselves, are also crudely labelled and insulted as having "transphobia" or "internalised transphobia." This strategy implicitly assumes that all transgender people think one way and all TERFs or conservatives think another way, therefore attacking someone based on their epistemology won't harm a transgender person. Actually, I asked "isn't 'trans women are women' a tautology" purely for the purpose of understanding my own experience. I cannot accept that I had a psychological phenomenon whose definition is a tautology. "A woman is a person who self-identifies as a woman" is the most extreme form of obscurantism, and I would prefer to accept "I am crazy" rather than believe in such a theory. I need a clear, noncircular definition of "gender identity." It is extremely crucial for my existence.

#textcite(<Kant1996Answer>) proposed the famous definition of Enlightenment, 
"_Enlightenment_ is the human being's emergence from his self-incurred minority. 
Minority is inability to make use of one's own understanding without direction from another. 
This minority _is self-incurred_ when its cause lies not in lack of understanding but in lack of resolution 
and courage to use it without direction from another." 
The emergence is accomplished not in other ways, but only in _Sapere aude_ (dare to know). 
This motto is not only epistemological, but more importantly, ethical and political.

#textcite(<Kant1996Answer>) gave three examples of "minority," 
"... a book that understands for me, a spiritual advisor who has a conscience for me, a doctor who decides upon a regimen for me ..." 
This is a precise description of the communities I encountered. 
Though they loudly proclaim their opposition to authority, they haven't actually escaped what Kant called "minority." 
They've simply changed their "guardian." 
The previous guardian might have been the church, tradition, or a monarch. The current guardian is Foucault or Butler's theory.

When they see somebody with a different opinion, they don't need to use their curiosity to ask, 
"What did they say? Why did they reach this conclusion?" 
Instead, they open their handbook. 
The handbook reads: "Using biology to explain gender = gender essentialism = oppression; transgender + gender essentialism = internalised transphobia." 
Thus, the comprehension ends. 
They let a theory framework understand others for them, hiding behind their guardian (the theory), abandoning the ethical responsibility to others.

Admittedly, understanding does not necessarily lead to ideal communication and consensus; 
they might still refuse my theory even if they read it, just like I refused theirs. 
Nevertheless, "Knowing" others is the first step of communication. 
Even if we still refuse each other's theory, at least we can reach a _meta-consensus_: 
I support $A$, while you support $B$, we cannot agree with each other because of $C$. However, unfortunately, they did not participate in a mutual dialogue. The asymmetry is manifested in the fact that I invested huge intellectual effort to understand them, while they did not do the same thing to me.

I believe that my research in biology and my attempt to comprehend their philosophy, though methodologically different, share a common epistemic root: a _Sapere aude_ characterised by pure wonder and curiosity.

"Dare to know" is a kind of modesty, because its presupposition is "I NEED to know," acknowledging our own epistemological deficiency. 
This is the drive to bridge the gap between the self and the external world, and the yearning to approach truth. 
Love of Truth and Love of Neighbour are fundamentally connected. 
Scientists acknowledge that nature is the "other," possessing its own logic independent of human will. 
Studying nature means humbly listening to its voice and understanding its laws, independent of our own. 
Similarly, true understanding of others means acknowledging them as independent rational beings with their own theories I have not yet comprehended. 
Reading their theories, as I have done, is "daring to know" their world, even if it would make me uncomfortable #footnote[I really felt uncomfortable with their writing style. While I think I must understand them, otherwise I am not qualified to write this section.]. 
// They abandoned this curiosity along with abandoning science, allowing a guardian to understand others on their behalf.
// %"Knowing" is essentially respecting and asking favours from others.

We need to acknowledge not only our epistemological deficiency regarding nature and of others, but also our deficiency of ourselves. 
My analysis of my own gender identity is precisely "dare to know." I did not "disrespect" my subjective experience.
Otherwise, I would have simply said, "How could I be a girl? It seems that I'm crazy. Period." 
On the contrary, I analysed my subjective experiences of gender dysphoria and gender euphoria very seriously, placing them on the same epistemological level as all other knowledge. 
My subjective experience received the highest respect I could give to knowledge. 
When you abandoned reason, logic, and science, abandoned _Sapere aude_, you also abandoned your responsibility to understand others and yourselves.

///-----------------------------------------------------------------
/// 
// An Asian, transgender, gender-abolitionist, anti-essentialist, working class (my mother was a textile worker, and my father is a machine worker) evolutionary biologist is clearly a multi-dimensional "Other," whether to conservatives and TERFs (obviously), liberals (they like the "born this way" narrative), the traditional academic community (I oppose both some conservative biologists' "scientific" gender essentialism and the "scientific" practice of searching for a "neurological proxy" for "gender identity"), the feminist philosophy of science (I agree with many of their scientific models, such as #posscite(<Zabalegui2024After>). However, I strongly oppose their "standpoint epistemology." #posscite(<Zabalegui2024After>) neurological model is correct only because it corresponds an external reality. If there is something that only specific people can see, it is definitely not a truth but a fallacy), the mainstream essentialist transgender community (they believe in an internal, essential gender identity), or the mainstream anti-essentialist transgender community (they are often post-structuralists, like to talk about discourse and power, and are wary of people who talk about science) ... I have never seen post-structuralists stand with this kind of politically useless "Other." They only support "Others" who comply with their philosophical stance.

// // %Peer review presupposes the existence of public standards. The very act of submitting a paper to peer-review implicitly acknowledges that there exists a public standard that transcends positions and can be commonly understood and judged. Without this public standard, peer review becomes purely a matter of "taking sides" -- "if you are one of us (whether this 'us' is divided by economic interests, academic factions, or 'lived experience'), I'll pass you; if you are not, I'll reject you." Although this situation does exist in reality, at least in theory, this is not the stated purpose of peer review.

Although the framework I use is evolutionary biology, neuroscience and cognitive science, my personal experience can be described perfectly well using Butler's gender performativity, Althusser's "interpellation," and Foucault's diffuse power and discipline (I am actually fully capable of rewriting this article using their frameworks and terms, see @app-ps-aeb). My views and post-structuralism point to the same conclusion: identity is constructed in interaction with the internal and external environment, not an innate, fixed, _a priori_ essence. The more I understand their theory, the more I cannot understand why they attacked me. 

// My views were rejected, most likely because I broke a discourse monopoly. In their eyes, the form is more important than the content. What kind of gender-view I actually described is irrelevant; what matters most is what language I used to say it. In that specific ideological framework, only discourse originating from specific thinkers is considered "orthodox" and "safe." Scientific discourse, even if it reaches similar conclusions, is seen as a "heretical," unwelcome external competitor. It threatens the purity and authority of that closed theoretical system.
// //  The tools of critique are no longer used for difficult and painful analysis; they have become obscure postmodern jargon, a sophistry to dismiss any criticism as "you don't understand," and a way to show allegiance to the tribe.

// Another reason is that they view so-called "logocentrism," "scientism," "rationality," and "grand narratives" as a form of oppression even more terrifying than patriarchy and sexism. So much so that when they encounter someone speaking scientific language, who could originally be a companion of them, they immediately turn their guns on them, completely ignoring the fact that we have the same enemy. This is precisely an ideological grand narrative. #textcite(<Lyotard1994Postmodern>) argued that "postmodernism is the incredulity of all metanarratives." However, "incredulity of all metanarratives" itself has become an unquestionable metanarrative -- I understand that the self-reference of relativism is a very classical and old-fashioned critique that can be dated to Plato's critique of sophists. While in my case, it has truly become a new "metanarrative" that caused real exclusion and violence. No sophisticated arguments can easily justify it.

// Post-Structuralists, queer theorists, and the communities influenced by them claim to protect the "Other" and respect "lived experience." #footnote[Butler being interviewed by #textcite(<Williams2014Gender>): "I think I needed to pay more attention to what people feel, how the primary experience of the body is registered, ..." 
// #textcite(<Butler2025Who>): "'Gender identity' is a deeply felt sense of how one fits in the gendered scheme of things, the lived reality of one's own body in the world".] However, in fact, they respect only those experiences consistent with their own theoretical and ideological framework. A rational, physicalist, gender-abolitionist, non-binary biologist trying to understand their own experiences and feelings in their own way does not seem to constitute a valid, respectable human experience in their eyes. Furthermore, my critique of cooking and kinship as a child should absolutely be considered a valid personal experience of universalism and rationalism, which are criticised as "logocentrism" or "epistemological hegemony."

// They claim to respect human experience, but they arbitrarily set boundaries to maintain the absolute authority of a specific kind of experience, and systematically disrespect, censor, and suppress all other conflicting experiences. What they seem to do is "finding a marginalised group, assimilating them with their theoretical framework, making them understand their experience with the post-structuralist terms, and ultimately expelling those who refuse post-structuralism." Is it "empowerment" or a form of intellectual colonisation?

// // According to Foucault's definition of power, a queer theorist who teaches at a top university, can influence the thinking of a generation of students, can decide the academic future and fate of students, defines what are "valuable" questions and "legitimate" research methods in a specific field, publishes articles in famous journals, and is honoured by medias as a "progressive thinker," should also be considered an essential node of power. Their self-proclaimed role of "speaking for the marginalised," claiming to be on the margins of "power" and the Other, is sociologically untenable. From a Foucauldian perspective, this self-claiming is not an objective description of power, but a power strategy that attempts to produce authority for themselves. Similarly, the mainstream liberal transgender community produces the "innate gender identity" through discursive effect and, through a series of social movements, implements its own political claims into written law, setting the threshold for community recognition, medical resources, and legal identity. This is also a form of power. They are not powerless victims, but an actively operating "regime of truth."

// // However, post-structuralists rarely include themselves in the list of "powers" when analysing the operation of power. They always use external power to define the "centre" and the "Other." When essentialist transgender people (e.g., the mechanical materialist "gender brain" or the idealist "gender soul") declare "do not deconstruct our gender identity," queer theorists tend to become very gentle and retract to an essentialist position (as in~\cite{Williams2014Gender}), even if they theoretically disagree with these people's essentialist claims (as in~\cite{Butler1990Gender}).

// // This is not an accident, but an inherent structural problem of their narratives. Because the size of a politically effective group has the lowest limit (although this is not a mathematically precise boundary). If post-structuralists want to maintain the political effectiveness of their actions, they must stop when they touch this lowest limit. Therefore, those who ultimately receive the most attention and protection are definitely not the most special, most vulnerable, and most excluded people, but a self-declared "minority" group that is large and major enough to make the loudest sound and form effective political movements.

// // If they consistently applied their own philosophy, they would have to stand with the "Other" of the dogmatic transgender community, and then, after these Others have formed a power, continue to stand with the Other's Other ... until one day, they must stand with the individual. In this way, they would return to the position of individualism and universalism.

// If they truly respect "lived experience," most people's (even scientists) subjective raw feeling is that the earth is flat and still, that spicy is a sense of taste, that we have a complete, unified, innate self-awareness, but almost no one rigorously respects these subjective experiences. Including post-structuralism itself, from Foucault onwards, its foundation is the systematic negation of the subjective experience of a "complete self-awareness." If they defend themselves by saying "the rational subject is a social construct that originated in the 18th century" @Foucault1994Order, then gender identity is exactly the same, a social construct that originated in the 20th century, thus should also be deconstructed as they did with the "rational subject."

// The respect for "experience" by post-structuralism and its branch, queer theory, is highly selective, conditional, and full of unstated political considerations. It is not a consistent principle. They are actually executing a hidden rule: "We respect those subjective experiences consistent with our philosophy and political agenda." As revealed by my experience, what they love is the abstract "other" -- the "conceptualised other" that exists in their theoretical texts, fits their narrative, and can be used to prove the "oppression of logocentrism."

// The reason is simple. For questions about the shape of the earth, whether spiciness is a taste or pain, and the formation of self-identity, the scientific conclusions are unequivocal. Doubting these things would immediately associate them with anti-science conspiracy theories like "flat-earth theory" and would make post-structuralists lose all credibility. In contrast, gender identity is still a complex and controversial area in neuroscience and cognitive science, far from reaching a definitive conclusion. This is a kind of "critique in the gaps" like "God in the gaps." They claim to be "postmodern," but their behaviour in this regard is very pre-modern.

// This is, in fact, a Cartesian mind-body dualism. They claim to oppose Descartes, but they have secretly resurrected Descartes's ghost, attempting to preserve a domain in human consciousness that is exempt from the tests of natural science, arguing that the general scientific methodology based on empirical evidence is invalid in this category. This is a pre-modern fantasy doomed to fail.

