#import "../lib.typ": *

Many people believe that we can abolish gender stereotypes while protecting gender identity, and we should create more different gender identities to include diverse experiences. #textcite(<Cull2024What>) framed it as "gender pluralism." In this section, I will demonstrate that this idea is both cognitive scientifically and mathematically impossible.

As we previously argued, gender identity is the product of socialisation within a gender norm based on stereotypes. One self-identifies with a gender because this label is meaningful rather than an empty signifier. Nobody self-identifies with "yhutabikoper" (an arbitrary word I created by pressing the keyboard randomly). An identifiable gender label must be associated with specific biological, psychological, aesthetical stereotypes to create predicting error and force us to update our self model. Therefore, protecting a "gender identity" only about self-identification and abolishing all gender stereotypes is infeasible.

The concept "gender" actually encompasses a considerable amount of extremely heterogeneous content: personality, clothing style, game type, toy type, division of labour in the family, occupation, behavioural habits, aesthetics ... For the convenience of analysis and calculation, we only consider personality traits here. The number of words used to describe personality traits is at least in the thousands @Allport1936Trait, and their combinations can produce an exponential explosion. By associating heterogeneous biological, psychological, aesthetical meanings with a limited number of gender labels, it restricts the available combinations, making most of them invisible and unusable. The practice of gender pluralism cannot resolve this issue. Considering that some of these personality trait terms are incompatible -- for example, a person cannot be both extroverted and introverted -- we take an extremely conservative estimate, assuming a total human personality pool of $N=100$, with each person possessing only 5 traits. The number of combinations of choosing 5 traits from 100 is $C_100^5 = 75,287,520$, which exceeds the total number of vocabulary in English and personal vocabulary sizes @Brysbaert2016Many@Collins2023English. It is information-theoretically impossible to map every unique identity to a discrete, socially usable label. This creates a cognitive inequality. People might remember "Man/Woman," and barely remember "Trans/Non-Binary/Queer," but we absolutely cannot remember 75 million microlabels. This strategy inevitably leads to newcomers being forgotten and ignored. Therefore, this strategy is a linguistic "enclosure movement" that inherently and structurally privileges some combinations, while marginalising others.

Gender pluralism self-declares to be the so-called "gender Marxism" @Cull2024What, while they are actually very idealist, completely ignoring the material reality and scientific mechanisms.

As a case in point, the status of xenogender in the current system is a typical manifestation of this linguistic "enclosure movement." It is considered "the other of the other of the other" (gender identities $supset.eq$ non-binary gender $supset.eq$ xenogender $supset.eq$ a specific xenogender, like raccogender). The diversity and internal heterogeneity of the xenogender are far greater than the typical gender identities, and the sources of the words also cover a much wider range (raccogender, parrotgender, and lizardgender already cover the entire Amniota; men and women, as part of _Homo sapiens_, are biologically parts of it). This classification is extremely unnatural and anthropocentric.

It should be noted that I do not oppose xenogender as a practice, in fact, I considered my self a raccoon. I am arguing that xenogender should not be understood as gender, but should rather be considered the act of "an individual choosing a word to describe themself." It is something greater, more creative and interesting than "gender," analogous to the art name (_hào_) of ancient Chinese artists, poets and writers. It is the direct product of our self-awareness and linguistic ability. It linguistically covers all possible words. Outside of it, we have no way to describe and define ourselves. It is what made us human beings, the organism with reason. This is the prerequisite for the birth of "gender identity" and even the gender construct. Gender identity is essentially just a small part of xenogender, which is a narrow identity that specifically uses a few specific words. The greatest guilt of "gender identity" is its attempt to elevate itself to a supreme position, even above the very thing that makes its existence possible.

Xenogender is neither "xeno-" (strange) nor "-gender" (gender). On the contrary, this is the broadest, freest self identity, the "meta-identity." It is the basic, purest, freest, and most unrestricted "identity." The Earth is not the centre of the universe; it is just a planet in the solar system. The solar system is just a part of the Milky Way. The stars and nebulae on that "outermost celestial sphere," once considered distant and unimportant, are the real universe.

