#import "../lib.typ": *

Critics might oppose my previous statement that "neither feminism nor LGBTQ has opposed gender-centrism," claiming that "queer theory is against gender-centrism." I admit that queer theory is ontologically anti-gender-centric, as argued by #textcite(<Butler1990Gender>) that they do not consider "sex" (phenotypic sex) or gender to be natural, real or stable. Still, there is a huge difference between ontology and methodology.

#textcite(<Butler1990Gender>) advocated for a strategy of "repeating":

#quote(block: true)[
    The task is not whether to repeat, but how to repeat, or, indeed, to repeat and, through a radical multiplexing of gender, to displace the very gender norms that enable the repetition itself.
]

The issue is neither _whether_ to repeat nor _how_ to repeat, but _what_ to repeat. For example, drag is a kind of repetition, however, this is precisely because we have gender norms about "what clothes men/women should wear." Nobody would use a strange desk as a kind of "subversive repetition," because there is no gender norm about desks. This strategy recognises the gender norm's power to define the area and boundary of the battlefield. Even "subversive" repetition is still a "repetition," therefore operates within the boundaries defined by "gender." Queer theory is ontologically anti-gender-centric yet methodologically extremely gender-centric. The intended outcome of this strategy was to "displace the very gender norms" by showing their constructed and unstable nature. However, as the actual outcome, by constantly talking about and analysing gender, by "repeating" gender inside the boundary, it has reinforced "gender" as the central issue for understanding ourselves and society. "Gender" was originally just an external sociocultural construct, but it is now frequently used as a synonym of "gender identity," an internal psychological phenomenon, and one must define themself by interacting with gender. For example, Butler used the word "gender" interchangeably with "gender identity" in an interview @Williams2014Gender, which is a category error that confused an abstract sociological concept with a psychological phenomenon. #textcite(<Oberle2023Benefits>) is also a typical case, they argued that using the word _gender_ to describe plants "harms" transgender people. It is the same category error to claim that the borrowing of an abstract sociological concept, _gender_, will "harm" humans who possess a psychological phenomenon, _gender identity_.

Similarly, creating many new third-person pronouns has nothing to do with "affirming self-identification." It is only because of the gendered third-person pronouns in English (and other Indo-European languages). However, gendered third-person pronouns themselves are an unjustified arbitrary social norm. If somebody propose a new second-person pronoun and demand all people use it rather than "you" to communicate with them, their demand will definitely not be respected. The so-called "freedom" or "liberation" is permitted by the gender construct, therefore reproducing the gender norm itself.

Moreover, it constitutes a cultural invasion upon languages without gendered third-person pronouns. Chinese originally lacked gendered third-person pronouns. Before the New Culture Movement, 他 (_tā_, will be mentioned as "neutral _tā_" in the following text) referred to anyone, regardless of gender. During the Westernisation wave in the 20th century, Liu Bannong created 她 (_tā_, she, will be mentioned as "female _tā_" in the following text) in 1917 to mirror the gendered pronouns in European languages, especially English. This sparked controversy; for instance, the magazine _Women's Resonance_ (妇女共鸣) argued that replacing the "human" radical (亻) with the female radical (女) from the neutral _tā_ to create the female _tā_ dehumanised women. Nonetheless, the utility of the distinction, especially in translation and new literature, led to its widespread adoption. Ironically, some "modern Liu Bannongs" brainwashed by the West propose creating a "gender-neutral pronoun" to mirror English's _they_. I am not a linguistic purist. I completely accept reasonable loanwords. However, gendered pronouns is not a reasonable case. It is not a natural and equal language contact, but a linguistic pattern that continuously replicates in history: imitating English pronouns, making English almost the "upstream" (in the software engineering sense) of Chinese. It is clearly a continuation of the old binary gender system, playing the same role in intercultural relations, imposing the Western gender system onto third-world cultures. It is not a subversion or rebellion against power, but rather the newest and most sophisticated form of the old power structure -- gender-centric ideology.

Queer theory's strategy was to engage gender norms on the "battlefield" which was defined by itself. The unintended consequence of this engagement was that the battlefield itself -- the very concept of "gender" -- became more central, omni-encompassing, and ideologically powerful than ever before, attracting everyone to join it. The strategy recognised the prison's power to define its walls, and sought to "destabilise" them by painting them many colours, but not destroy and escape from it. The outcome was that the "colourful and comfortable" prison became more fundamentally entrenched, attracted more and more people to move in and reinforcing the core idea that one must be a prisoner. If a theory operates only within the field permitted by the existing social order, it is essentially defending this order, thus losing its ability to critique the social injustice.

Although Butler themself opposes identity politics, the aforementioned gender pluralism is arguably influenced by this strategy. Because they created a powerful cultural incentive: to treat all kinds of unconventional personal experiences and identities as a "gender", because it has made "gender" the most attractive "liberative" discourse. If "gender" were still strictly understood as a social construct (its original sociological definition), xenogender people would likely not see their "identity" as a "gender identity." They do so because "gender" is currently the most prominent and available discourse of resistance. This paradoxically expands the category of gender to encompass phenomena that might otherwise have been understood in different categories (e.g., as personality, philosophy, or simply as radical individuality). 
// Within the xenogender community, there is already reflection on this issue, and the alternative term xenoidentity has been proposed for those who have similar identities but are unwilling to classify it as a "gender identity."

This theory is politically conservative, even reactionary, because by repeating gender, it obscures the more fundamental question of "why gender itself exists," preventing people from seeing and challenging the system itself. Reformism, through welfare systems and class mobility, transformed the revolutionary anger of the proletariat into dependence on the existing system, thus eliminating the motivation for revolution @luxemburg1986Reform[Chapter VIII]. Similarly, queer theory, though believing itself to be resisting, is actually helping the gender system to fix its bugs by expanding "gender," making it more diverse, inclusive and fluid, therefore bringing those who did not conform to the gender system back under its governance and eliminating the motivation for abolition.

// %The proliferation of micro-labels (e.g., demiboy, genderfluid) can also be considered a "subversive repetition" of traditional gender labels like "man" and "woman." Although they were created to show the instability of "man" and "woman," it has now become an attempt to categorise every nuance of personality within the framework of "gender," thereby strengthening the very construct of gender-centrism.
// %As #textcite(<Marx1977Critique>) said in his _A Contribution to the Critique of Hegel's Philosophy of Right_:
// %
// %\begin{quotation}
// %    Luther, we grant, overcame bondage out of _devotion_ by replacing it by bondage out of _conviction_. He shattered faith in authority because he restored the authority of faith. He turned priests into laymen because he turned laymen into priests. He freed man from outer religiosity because he made religiosity the inner man. He freed the body from chains because he enchained the heart.
// %\end{quotation}
// %The concept of "gender identity" leads individuals to equate a social construct with their true self, to internalise an external social construct as a core part of their self. It freed the body from "gender" because it enchained the heart. It successfully achieved what classical gender theory could not do for thousands of years.
// %
// %If the gender system cannot accommodate our existence, shouldn't we completely smash this system? Why must we tell them, "Actually, we are also a kind of 'gender'?" By saying "we are also a kind of 'gender'," they have accepted that "gender" is a valuable category worth joining, which gave up the fundamental right to ask, "Can we abolish the social norm centred on 'gender'?" #textcite(<Butler2025Who>) is a typical figure of this reformist ideology:
// %
// %\begin{quotation}
// %    The critique of the gender binary, for instance, did not claim that "women" and "men" are over and done with. On the contrary, it asked why gender is organized that way and not in some other way. It was also a way of imagining living otherwise. The critique of the gender binary turned out to give rise to a proliferation of genders beyond the established binary versions -- and beyond the gender hierarchy that feminism rightly opposes.
// %\end{quotation}

In an interview with #textcite(<Williams2014Gender>), Butler claims that "some people really love the gender that they have claimed for themselves. If gender is eradicated, so too is an important domain of pleasure for many people. And others have a strong sense of self bound up with their genders, so to get rid of gender would be to shatter their selfhood." Similar viewpoints are also found in the analytical tradition: #textcite(<Cull2019Against>), who supports the aforementioned "gender pluralism," argued that "A genderless society is harmful to transgender people by refusing to recognise their identity." However, the fallacy is that Butler and Cull presumed the existence of "transgender people" as an immutable and transhistorical category that will persist in a society where the concept of gender no longer operates, which is typical gender essentialism. It is the same as saying, "We need to use pathogens to make vaccines, so eliminating pathogens would harm the patient's life," ignoring the fact that there will not be patients in an apathogenic environment.

I do not shy away from this point: according to my model, in a world where gender is abolished, transgender people will not exist. Cisgender people will also not exist. Because "assigned sex" and "gender identity" will not exist, which are necessary in the definition of "transgender" and "cisgender." However, this is not an elimination of contemporary transgender people, nor does it mean that healthcare for contemporary transgender people is not needed. Quite the contrary, this is based on a profound acknowledgement of the suffering of contemporary transgender people (including myself). The root cause of the suffering (such as gender dysphoria) and oppression is the social construct about gender. Transgender status is not an individual condition stemming from an "inner self" that requires medical care #footnote[I fully acknowledge that body representation incongruence is an internal body condition requiring medical treatment. However, as we previously argued, considering it "gender identity" is a category error. In my envision, one may just go to a doctor and say, "I have a persistent rejection of this part, it affects my life, and I want to remove it to resolve my suffering." ], but a serious political threat to our very existence. Insisting on "gender identity" is to treat only the symptoms while allowing the pathogen (the gender construct) to persist. True liberation is not achieved by merely managing the symptoms while allowing the pathogen to thrive. It requires eliminating the pathogen altogether. It is not to defend the identity of "transgender" but to achieve a world where such categories are no longer necessary to describe human experience. Gender abolitionism is the only systematic solution, as it correctly identifies the problem in the socialisation that shapes all individuals.

It is clearly impossible that something "someone finds meaning in" should be protected. Some housewives find meaning within the patriarchal gender division of labour; some users genuinely find joy in short videos; some fans really enjoy the movies produced by cultural industry ... Are all these things in need of protection? Therefore, "someone finds meaning in it" is not a sufficient condition of "it should be protected."

In fact, "eliminating" (in this specific sense) transgender status requires no grand social engineering like gender abolition. Simply stopping birth sex assignment is enough to dismantle the cisgender/transgender binary entirely, as their definitions are contingent upon the "assigned sex." Here lies the irony: if anything that invalidating  "transgender" condition is "transphobic," abolishing birth sex assignment invalidating "transgender" condition, then birth sex assignment is "transphobic." The transgender community should fight to protect birth sex assignment rather than opposing it. The original assumption leads to a contradiction, proving that Butler and Cull's opposition to gender abolitionism is logically invalid. It proves that a political proposal that logically invalids transgender condition does not necessarily harm transgender people, it can also be liberatory to us.

The two aforementioned points demonstrated that this theory paradoxically relies on the system it opposes. As I previously argued, this is precisely because of the ontology of post-structuralism. They do not believe that the objective knowledge of the external world is possible. Therefore, the goal is not to match an external truth, but to play with, subvert, and reconfigure the discourses we live within. By rejecting the premise of objective knowledge, they finally strengthened gender-centrism. In contrast, an objective understand of the reality is possible and desirable in scientific realism, which provides an unshakeable foothold for scientific and philosophical criticism and political resistance: the concept of "gender" causes most people's perception of the world to be inconsistent with this external, objective reality. So it must be abolished. Science reveals the "true nature" of the world, thereby stripping oppressive social systems of their legitimacy.

Ironically, #textcite(<Butler2025Who>) compared transphobia with climate change, environmental problems, which are, however, revealed by science. This means that Butler thought that science is able to establish truth and serve as a foundation of liberatory political ections, at least in some specific fields. It seems that Butler also respects science in these fields. Why cannot it play the same role in the gender issue?

// The highest goodness and truth is about aligning our internal models with external reality. This is a concise demonstration of the fundamental, irreconcilable gap between the scientific worldview of Enlightenment and the post-structuralist one.
