#import "../lib.typ": *

// Critics might accuse me, "your theory is just a wrap of queer theory with analytic and scientific languages." I admit that my model is similar with #posscite(<Butler1990Gender>) theory in some senses, including denying a Cartesian self and supporting a constructed/shaped self-consciousness by the external environment through discursive effect/neuroplasticity. I believe that we are actually describing the same process from different perspectives and levels. 

// From a scientific realistic aspect, gender shapes our understanding about the biological, psychological and sociological diversity of human beings, which is inconsistent with its real mathematical structure. This misunderstanding, also known as "stereotype," affects our self-identity. 

As an exception, I admit that queer theory is ontologically anti-gender, as argued by #textcite(<Butler1990Gender>) that they do not consider "sex" (phenotypic sex) or gender to be natural, real or stable. Still, there is a huge difference between ontology and methodology.

#textcite(<Butler1990Gender>) advocated for a strategy of "repeating," they said that "The task is not whether to repeat, but how to repeat, or, indeed, to repeat and, through a radical multiplexing of gender, to displace the very gender norms that enable the repetition itself." However, I'd say that the issue is neither _whether_ to repeat nor _how_ to repeat, but _what_ to repeat. For example, drag is a kind of repetition, however, this is precisely because we have gender norms about "what clothes men/women should wear." Nobody would use a strange desk as a kind of "subversive repetition," because there is no gender norm about desks. This strategy recognises the gender norm's power to define the area and boundary of the battlefield. Even "subversive repetition" is still a "repetition," therefore operates within the boundaries defined by "gender." 

Queer theory is ontologically anti-gender yet methodologically extremely gender-centric. The intended outcome of this strategy was to "displace the very gender norms" by showing their constructed and unstable nature. However, as the actual outcome, by constantly talking about and analysing gender, by "repeating" gender inside the boundary, it has reinforced "gender" as the central issue for understanding ourselves and society. "Gender" was originally just an external sociocultural construct, but it is now frequently used as a synonym of "gender identity," an internal psychological phenomenon. For example, Butler used the word "gender" interchangeably with "gender identity" in an interview @Williams2014Gender. #textcite(<Oberle2023Benefits>) is also a typical case, they argued that using the word _gender_ to describe plants "harms" transgender people. It is the same category error to claim that borrowing an abstract sociological concept, _gender_, will "harm" individuals who possess a psychological phenomenon, _gender identity_.

Similarly, creating many new third-person pronouns is also because of the gendered third-person pronouns in English (and other Indo-European languages). However, gendered third-person pronouns themselves are an unjustified arbitrary social norm. If somebody propose a new second-person pronoun and demand all people use it rather than "you" to communicate with them, their demand will clearly not be respected. The so-called "freedom" or "liberation" is permitted by the gender construct, therefore repeating the gender norm itself.

Moreover, it constitutes a cultural invasion upon languages without gendered third-person pronouns. Chinese originally lacked gendered third-person pronouns. Before the New Culture Movement, 他 (_tā_, will be mentioned as "neutral _tā_" in the following text) referred to anyone, regardless of gender. During the Westernisation wave in the 20th century, Liu Bannong created 她 (_tā_, she, will be mentioned as "female _tā_" in the following text) in 1917 to mirror the gendered pronouns in European languages, especially English. This sparked controversy; for instance, the magazine _Women's Resonance_ (妇女共鸣) argued that replacing the "human" radical (亻) with the woman radical (女) from the neutral _tā_ to create the female _tā_ dehumanised women. Nonetheless, the utility of the distinction, especially in translation and new literature, led to its widespread adoption. Ironically, some "modern Liu Bannongs" brainwashed by the Western gender theories propose creating a so-called "gender-neutral pronoun" to mirror English's _they_, completely forgetting that the traditional neutral _tā_ itself is gender-neutral.

// I am not a linguistic purist. I completely accept reasonable loanwords. However, gendered pronouns is not a reasonable case. It 
This is not a natural and equal language contact, but a linguistic pattern that replicates in history: continuously imitating English pronouns, making English almost the "upstream" (in the software engineering sense) of Chinese. Otherwise, why doesn't English imitate other languages which have gendered first- or second-person pronouns? Japanese has gendered first-person pronouns, although it is semantic gender rather than grammar gender. If queer theorists really want to "repeat through a radical multiplexing of gender," why doesn't they use "self" (自分, _jibun_) as their first-person pronoun in English? 

// , imposing the Western gender system onto third-world cultures. 
// I believe that the third-person pronouns in Chinese should be restored to the neutral _tā_ before Liu Bannong. 

Therefore, most contemporary theories, including conservative gender binaryism, gender-critical feminism, liberalism, and transgender activism, are ontologically gender-centric. And queer theory is methodologically gender-centric. Neopronouns is clearly a continuation of the old binary gender system, playing the same role in intercultural relations. These theories collectively contribute to the reinforcement of gender-centric ideology and impose Western gender ideologies onto third world cultures. It is not a subversion or rebellion against power, but rather the newest and most sophisticated form of the old power structure -- gender-centric ideology. 

Queer theory's strategy was to engage gender norms on the "battlefield" which was defined by itself. The consequence of this engagement was that the battlefield itself -- the very concept of "gender" -- became more central, omni-encompassing, and ideologically powerful than ever before. The strategy recognised the prison's power to define its walls, and sought to "destabilise" them by painting them many colours, but not destroy and escape from it. The outcome was that the "colourful and comfortable" prison became more fundamentally entrenched, attracted more and more people to move in and reinforcing the core idea that one must be a prisoner. If a theory operates only within the field permitted by the existing social order, it is essentially defending this order, thus losing its ability to critique the social injustice. 

/* Although Butler themself opposes identity politics, the aforementioned gender pluralism is arguably influenced by this strategy. Because they created a powerful cultural incentive: to treat all kinds of unconventional personal experiences and identities as a "gender", because it has made "gender" the most attractive "liberative" discourse. If "gender" were still strictly understood as a social construct (its original sociological definition), xenogender people would likely not see their "identity" as a "gender identity." They do so because "gender" is currently the most prominent and available discourse of resistance. This paradoxically expands the category of gender to encompass phenomena that might otherwise have been understood in different categories (e.g., as personality, philosophy, or simply as radical individuality). 
// Within the xenogender community, there is already reflection on this issue, and the alternative term xenoidentity has been proposed for those who have similar identities but are unwilling to classify it as a "gender identity."

The so-called "radicality" of queer theory is primarily manifested at the discursive and normative levels: it deconstructs traditional gender norms, challenges heterosexual hegemony, opposes naturalized narratives, and emphasizes the role of power and discourse. However, it almost never truly addresses a more dangerous question: "Should this deconstructed object continue to exist as a basic unit of analysis?" In other words, in practice, queer theory often opposes norms but supports ontology. In this respect, it is not at opposite ends of traditional gender essentialism, but rather shares a deep premise: gender must exist, only in different forms.

This theory is politically conservative, even reactionary, because by repeating gender, it obscures the more fundamental question of "why gender itself exists," preventing people from seeing and challenging the system itself. Reformism, through welfare systems and class mobility, transformed the revolutionary anger of the proletariat into dependence on the existing system, thus eliminating the motivation for revolution @luxemburg1986Reform[Chapter VIII]. Similarly, queer theory, though believing itself to be resisting, is actually helping the gender system to fix its bugs by expanding "gender," making it more diverse, inclusive and fluid, therefore bringing those who did not conform to the gender system back under its governance and eliminating the motivation for abolition.

// %The proliferation of micro-labels (e.g., demiboy, genderfluid) can also be considered a "subversive repetition" of traditional gender labels like "man" and "woman." Although they were created to show the instability of "man" and "woman," it has now become an attempt to categorise every nuance of personality within the framework of "gender," thereby strengthening the very construct of gender-centrism.
// %As #textcite(<Marx1977Critique>) said in his _A Contribution to the Critique of Hegel's Philosophy of Right_:
// %
// %\begin{quotation}
// %    Luther, we grant, overcame bondage out of _devotion_ by replacing it by bondage out of _conviction_. He shattered faith in authority because he restored the authority of faith. He turned priests into laymen because he turned laymen into priests. He freed man from outer religiosity because he made religiosity the inner man. He freed the body from chains because he enchained the heart.
// %\end{quotation}
// %The concept of "gender identity" leads individuals to equate a social construct with their true self, to internalise an external social construct as a core part of their self. It freed the body from "gender" because it enchained the heart. It successfully achieved what classical gender theory could not do for thousands of years.
// %
// %If the gender system cannot accommodate our existence, shouldn't we completely smash this system? Why must we tell them, "Actually, we are also a kind of 'gender'?" By saying "we are also a kind of 'gender'," they have accepted that "gender" is a valuable category worth joining, which gave up the fundamental right to ask, "Can we abolish the social norm centred on 'gender'?" #textcite(<Butler2025Who>) is a typical figure of this reformist ideology:
// %
// %\begin{quotation}
// %    The critique of the gender binary, for instance, did not claim that "women" and "men" are over and done with. On the contrary, it asked why gender is organized that way and not in some other way. It was also a way of imagining living otherwise. The critique of the gender binary turned out to give rise to a proliferation of genders beyond the established binary versions -- and beyond the gender hierarchy that feminism rightly opposes.
// %\end{quotation}

*/
