#import "../lib.typ": *

Since the real problem lies in an omni-encompassing ideology that attempts to assign "gender" to everything, the most fundamental solution is to abolish the whole gender construct. I hereby propose a solution aiming at abolishing gender by strictly limiting or dismantling "sex" and "gender" to atomic entity, detaching them from individuals.

The biological sex should be strictly confined to the gametes @Lehtonen2014Gamete@Goymann2023Biological@Hurst1996There@Griffiths2025Biology. 
//It is related to, and only to, gametes. Individuals do not have such a sex. 
Sexual dimorphism is a dynamic spectrum that constantly changes throughout evolutionary history. The so-called "phenotypic sex" should be dismantled into a series of discrete, decentralised, atomic phenotypic traits such as chromosomes, hormones, as well as all morphology and anatomical traits. They are distributed on the sexual dimorphism spectrum, along with other sexually dimorphic traits not traditionally classified as "sex" (phenotypic sex), like height, weight, body hair, and body fat percentage @Wells2007Sexual. The phenotypic sex, as a distinct, independent entity, should be dropped. Individuals do not have an innate gender; they merely "possess" gametes and sexual dimorphic traits, "live in" a society and "internalise" the gender construct.
// The imprecise concept of intersex should be replaced by more detailed terms like intergonadal, intergenital, and sexual intermorphism. Gender should be strictly treated as a sociocultural phenomenon.

#textcite(<Parvin1982Ovulation>) reported a person who was completely "phenotypic male" and had fathered a daughter, but one of their two "testicles" was actually a pure ovary (not an ovotestis), and dissection showed it had previously ovulated. Therefore, most people, even those who have had children, cannot know for sure whether they are capable of producing two types of gametes. By biologically confining sex strictly to an unobservable trait, it cannot be "assigned" or "inferred." This makes it lose any possibility of being used for social classification, discipline, and oppression. It becomes a technical term of reproductive biology, completely "exiled" from politics and our daily life.

It should be noted that my proposal is completely different from conservatives, who claim to adopt gametic definition, but still rely on the genital in practice, which is self-contradictory. This even includes some conservative scientists, like #textcite(<Sokal2024Sex>), who claim that sex is an "objective biological reality," "determined at conception and observed at birth." I agree that sex _sensu stricto_ is an objective biological reality, and is strictly binary in Vertebrata. While according to #textcite(<Jones2006Gamete>), "Conception occurs when a sperm and an ovum fuse to become a zygote." "The process of fertilisation, or conception, involves fusion of the nucleus of a male gamete (sperm) and a female gamete (ovum) to form a new individual." At "conception" (fertilisation), one was just a zygote, a single cell. It has neither sex _sensu stricto_ because it cannot produce its own gametes, nor does it have phenotypic sex since it lacks a developed body. Even if its genome guides it to develop into a typical phenotypic male or female under normal conditions, it will not necessarily be so. For instance, if a 46, XY zygote loses its Y chromosome during the first mitotic division after fertilisation, it will develop into a 45, X0/46, XY chimaera (mixed gonadal dysgenesis) or a 45, X0 individual with Turner syndrome @Gravholt2017Clinical@Jacobs1997Turner@Lopes2014Mosaicism.

I recognise that the binary sex is still a very useful model in evolutionary biology, ethology, and reproductive ecology. It is obviously technically and ethically impossible to capture and dissect all individual animals to examine the gametes they produce. In these cases, researchers should state in their _Materials and Methods_ section what proxy they used to estimate the gamete production capacity and the reliability, such as the situation in birds demonstrated by #textcite(<Hall2025Prevalence>). Sex _sensu stricto_ itself is a technical term for a microscopic reproductive biological trait, not an externally observable morphological character.

// %\textcite{Polderman2018Biological} claimed that the heritability of gender identity is 30--60\% and consistent with other behavioural and personality traits, which is a category error. As we have said before, "gender identity" cannot be encoded in the genome (this would require extraordinary evidence). We can only have a series of genes related to personality traits, cognitive styles, and body representation. Studying the "heritability of gender identity" is a huge logical leap. The correct scientific questions should not be: "What is the biological basis of gender identity?" but rather: "Which heritable biological traits are assigned gender meaning by society and culture?" (sociology). "How does the meaning interact with the individual to construct a specific gender identity?" (psychology). "What is the biological basis of these traits?" (genetics and neuroscience). Autism spectrum disorder is also highly heritable \parencite{Sandin2017Heritability}, and autistic traits are higher in those working in STEM fields \parencite{Ruzich2015Sex}. Following \posscite{Polderman2018Biological} methods, we might also be able to calculate a mathematically reasonable number of "heritability of STEM ability", which everyone would consider an absurd study. Autistic neurological traits are heritable, while participating in STEM fields is an extremely complex result of innate neurological traits, personal experience, academic training and so on. Biological studies of "gender identity" are precisely the 21st-century replication of "scientific" racism.

At the social level, all gender concepts and any social constructs should be abolished. The biological characteristics previously considered "phenotypic sex" should have no more social significance than height or weight. All mention of gender in laws and regulations should be removed. In cases not involving a relationship, replace "man" or "woman" with "person." In cases involving a relationship (such as marriage), replace them with "one person" and "the other person." Gendered pronouns and titles should be abolished, sexual orientation should be considered mating preferences or aesthetic preferences, gender incongruence should be considered a form of body representation incongruence, and gender-affirming surgery should be considered a form of cosmetic surgery. A person's desire to change their body, whether because of innate body representation incongruence or any acquired factor, is a matter of pure personal freedom. These are merely mechanical modifications to our body, its legitimacy stems from bodily autonomy. It does not need an unprovable "gender identity" to justify it. Gender markers should be removed from all nonmedical records, and sex markers in medical records should be multi-level (chromosomes, reproductive organs, fertility, hormone levels, etc.) rather than just male/female. All gender-segregated facilities should be eliminated. Clothing stores should no longer be divided into "men's/women's" sections, but organised by clothing type (tops, pants, outerwear) and size/fit. Toys should no longer be divided into "boys'/girls'," but by function and type (e.g., building blocks, dolls, science experiments, art creation) and appropriate age.

Our goal is to make each word correspond to a single, logically atomic entity. If vagina is just vagina (an organ), pink is just pink (a colour), dress is just dress (a type of clothing), and introversion is just introversion (a personality trait), having no relation to each other, then all the different, mathematically possible combinations are equally accessible and usable.

// This transforms the issue from a special identity under identity politics, a special psychological state (identity), and a specific phenomenon, to the dismantling of an oppressive system. Everyone, whether "cisgender" or "transgender," is a victim of this system. It is a political issue that requires the participation of the entire society: why do bathrooms need to be segregated by gender, and why do documents need to be marked with gender?

