#import "../lib.typ": *

In an interview with #textcite(<Williams2014Gender>), Butler claims that "some people really love the gender that they have claimed for themselves. If gender is eradicated, so too is an important domain of pleasure for many people. And others have a strong sense of self bound up with their genders, so to get rid of gender would be to shatter their selfhood." Similar viewpoints are also found in the analytical tradition: #textcite(<Cull2019Against>), who supports the aforementioned "gender pluralism," argued that "A genderless society is harmful to transgender people by refusing to recognise their identity." However, the fallacy is that Butler and Cull presumed the existence of "transgender people" as an immutable and transhistorical category that will persist in a society where the concept of gender no longer operates, which is typical gender essentialism. It is the same as saying, "We need to use pathogens to make vaccines, so eliminating pathogens would harm the patient's life," ignoring the fact that there will not be patients in an apathogenic environment.

I do not shy away from this point: according to my model, in a world where gender is abolished, transgender people will not exist. Cisgender people will also not exist. Because "assigned sex" and "gender identity" will not exist, which are necessary in the definition of "transgender" and "cisgender." However, this is not an elimination of contemporary transgender people, nor does it mean that healthcare for contemporary transgender people is not needed. Quite the contrary, this is based on a profound acknowledgement of the suffering of contemporary transgender people (including myself). The root cause of the suffering (such as gender dysphoria) and oppression is the social construct about gender. Transgender status is not an individual condition stemming from an "inner self" that requires medical care #footnote[I fully acknowledge that body representation incongruence is an internal body condition requiring medical treatment. However, as we previously argued, considering it "gender identity" is a category error. In my envision, one may just go to a doctor and say, "I have a persistent rejection of this part, it affects my life, and I want to remove it to resolve my suffering." ], but a serious political threat to our very existence. Insisting on "gender identity" is to treat only the symptoms while allowing the pathogen (the gender construct) to persist. True liberation is not achieved by merely managing the symptoms while allowing the pathogen to thrive. It requires eliminating the pathogen altogether. It is not to defend the identity of "transgender" but to achieve a world where such categories are no longer necessary to describe human experience. Gender abolitionism is the only systematic solution, as it correctly identifies the problem in the socialisation that shapes all individuals.

It is clearly impossible that something "someone finds meaning in" should be protected. Some housewives find meaning within the patriarchal gender division of labour; some users genuinely find joy in short videos; some fans really enjoy the movies produced by cultural industry ... Are all these things in need of protection? Therefore, "someone finds meaning in it" is not a sufficient condition of "it should be protected."

In fact, "eliminating" (in this specific sense) transgender status does not require grand social engineering like gender abolition. Simply stopping birth sex assignment is enough, as the definition of it relies on the "assigned sex." Here lies the irony: if anything that invalidates "transgender" condition is "transphobic," abolishing birth sex assignment invalidates "transgender" condition, then birth sex assignment is "transphobic." The transgender community should fight to protect birth sex assignment rather than opposing it. The original assumption leads to a contradiction, proving that Butler and Cull's opposition to gender abolitionism is logically invalid. This proves that "a political proposal will logically invalidate an identity" is not a sufficient condition of "it harms corresponding people," it clearly can also be liberating to them. If anybody else want to argue that "abolishing gender will necessarily harm transgender people," they need to provide stronger arguments, rather than just rely on a proposition that has been falsified by a counterargument. 

This is precisely because of our ontological premise: I believe in an objective reality that exists independently of the human mind, and the objective knowledge of it, which is independent of culture and society, is possible, desirable, and pursuable. For queer theory, our understanding of reality is constructed through discourse and we cannot perceive it without mediation. In most contexts, ontology might be nothing more than a boring metaphysical intellectual game. While in this case, ontology is everything, it decides two completely different strategy. They do not believe that the objective knowledge of the external world is possible. Therefore, the goal is not to match an external truth, but to play with, subvert, and reconfigure the discourses we live within. However, there is clearly no scientific evidence to prove that human beings cannot be socialised without gender.   

By rejecting the premise of objective knowledge, they finally strengthened gender-centrism. In contrast, an objective understand of the reality is possible and desirable in scientific realism, which provides an unshakeable foothold for scientific and philosophical criticism and political resistance: the concept of "gender" causes most people's perception of the world to be inconsistent with this external, objective reality. So it must be abolished. Science reveals the "true nature" of the world, thereby stripping oppressive social systems of their legitimacy.

#textcite(<Butler2025Who>) compared transphobia with climate change, environmental problems, which are, ironically, revealed by science. This means that Butler agrees that science is able to establish truth and serve as a foundation of liberating political actions, at least in some specific fields. So why cannot science play the same liberating role in gender issues?

/*The two aforementioned points demonstrated that this theory paradoxically relies on the system it opposes. As I previously argued, this is precisely because of the ontology of post-structuralism. 

// The highest goodness and truth is about aligning our internal models with external reality. This is a concise demonstration of the fundamental, irreconcilable gap between the scientific worldview of Enlightenment and the post-structuralist one.

Therefore, once gender is abolished, gender identity will also disappear. This is not because I hate gender identity (in fact, I really enjoy my gender identity), but because gender identity cannot exist independently of gender stereotypes. 
//Therefore, we must choose between "preserving gender stereotypes in order to preserve gender identity" and "abolishing gender identity along with abolishing gender stereotypes," and I believe the latter is entirely worth the cost.

Both queer theory and I long for a space with infinite human creativity and freedom. 
This space may need a name, or perhaps it doesn't need a name. But it cannot be called "gender," because that is the name of the prison we are trying to escape from. 
The word "gender" clearly refers to an hierarchical social construct under patriarchy @pilcher2004key. Naming our self-identity "gender" would be like naming a nature reserve "slaughterhouse" or naming the peace "war." In my view, "gender identity," as in #posscite(<Marx1977Critique>) critique of Luther's Reformation, frees the body and enchains the heart. 
*/
