#import "../lib.typ": *

// As we said above, if we apply the standards of Aves to Mammalia, we will conclude that almost all humans are intersex. However, in the following argument, let's not jump to such a radical stage.

// Let's first achieve a kind of logical consistency within humanity: individuals with gynaecomastia are intersex. This is the necessary result of applying the standard of breasts as part of "phenotypic sex" from other domains to the domain of "intersex."

// Then, according to the old diagnostic criteria, like in ICD-10 @WHO1992ICD10 or DSM-IV-TR @APA2000DSM4, an individual with gynaecomastia who self-identifies as male should be considered a specific kind of transsexual (XtM), because they have "a sense of discomfort with their anatomic sex," and want to make it "as congruent as possible with one's preferred sex." The medical treatment should also be considered "gender affirming surgery." Ironically, both diagnostic criteria explicitly exclude intersex individuals, which is extremely hard to understand.

// However, rather than achieving greater inclusivity by including intersex people, the editors continue to maintain a _de facto_ exclusion of intersex people by introducing the concept of  "assigned sex at birth"@APA2013DSM5@WHO2019ICD11. Not only individuals with gynaecomastia were excluded from transgender, but many traditionally defined

The preceding biological analysis established that "gender identity" is not an internal essence housed within the brain or soul, but rather a product of neuroplasticity formed as the brain finds patterns in noisy and arbitrary social norms. "Gender identity" should be understood literally, "identity with a gender," which is shaped in one's interaction with and internalisation of social gender constructs. The psychotherapist should play the role of a philosophy and science teacher, promoting self-understanding in clients who are exploring their gender identity through Socratic dialogue. It's not about providing answers; it's about providing tools for thinking and empowering the individual to find their own answers. They are rational beings capable of and deserving of a deep, philosophical engagement with their own identity.

Some people may feel uncomfortable or frightened by this conclusion, but I would say that we have no need at all to shy away from "gender identity is the internalisation of social gender norms and gender stereotypes." (I even believe that my own gender identity is a product of childhood trauma, bullying, misnaming, and physiological diseases, see #plaincite(<Sun2025Autoethnography>)) The gender identity of cisgender people is also the internalisation of gender norms and stereotypes. When Gender Critical Feminists say "you are just conforming to gender stereotypes," we can simply respond: "Yes, I know I am. And you are also conforming to gender stereotypes when you advocate the so-called 'biological sex' (phenotypic sex)." 

However, its origin is politically unimportant. Why is it a virtue when childhood trauma causes a person to have a strong heart, but when it causes a person to develop an incongruent gender identity, it needs to be "converted?" This conservative logic is very easy to refute. What should be emphasised is: gender identity is an acquired psychological state, but it is acquired subtly and unconsciously, like the first language. For the persons themselves, it feels very "innate." (I also felt my gender identity very "innate" before I did a self-analysis.) This is how our brains work, it does not mean that we should blame people for "internalising gender stereotypes." 

Consequently, because the biological hardware is merely processing the software of culture, I shift the focus from the biological mechanism to the philosophical structure of the social constructs themselves. I will demonstrate that the contemporary theoretical framework surrounding gender -- specifically the dichotomy of "cisgender" and "transgender" and the concept of "assigned sex at birth" (ASAB) -- is full of internal contradictions to maintain a precarious ideological order.

Let us have a thought experiment: an intersex child is assigned female at birth, but gets lost at a very young age, is reassigned male by adoptive parents, and is raised as a boy. After adulthood, their body is closer to a "phenotypic male," but their gender identity is female. According to the definition of #textcite(<APA2013DSM5>, <WHO2019ICD11>), this individual is a "cisgender female."

By introducing the concept of "assigned sex at birth," some intersex people are excluded from transgender. Ironically, if we use "phenotypic sex" to define transgender people, we can capture this individual's unique gender socialisation experience (XtF) very well. Since the so-called "assigned sex" is almost always binary in actual medical practice, it simplifies the patterns of children's gender socialisation using two typical phenotypic sexes, replicating the power framework it seeks to oppose, and in fact, brings back the ghost of gender binary.

When we examine ASAB more further, we will inevitably ask: Is "assigned sex/gender at birth" #footnote[In English, both "assigned sex" and "assigned gender" are used. ] a kind of "sex" or "gender?" What is the relationship between ASAB and gender identity? If gender is unrelated to phenotypic sex, and gender identity is not identifying with sex, then logically, being phenotypic or assigned male/female and identifying as male/female are two or three unrelated things. They just share the words "male/female," like the ecological and sociological "community."

Therefore, everyone's phenotypic sex (a series of biological characteristics, although the scope is constructed) or ASAB (a label on a legal document) is "inconsistent" with their gender identity (a psychological state). Or more accurately, it is impossible to discuss whether they are "consistent" or "inconsistent.". Because they describe three essentially different kinds of things, just as we would not say that the social "community" a person belongs to is "consistent" with the ecological "community" they inhabitants.

Conversely, if those whose ASAB use the same word as their gender identity are called "cisgender" @Koenig2019Glossary, and their phenotypic sex or ASAB "aligns" or "is consistent with" their gender identity, this means that phenotypic sex and gender are related in some way. This demonstrates that when they need to separate the body from identity, they use nominalism; when they need to establish the cisgender/transgender binary opposition, they secretly retreat to an unreflective realist position.

The conflict between "nominalism" and "realism" occurs not only between ASAB and gender identity, but also within "gender identity" itself: is the "woman" of feminism and the "woman" of patriarchy the same concept? The "woman" who supports feminism and the traditional "woman" both self-identify as "woman." Are their gender identities the same? They claim that all people who identify as "woman" share some real, _a priori_ "essence" called "female identity", no matter how different their values, lifestyles, and political stances are, using realist labels like "cisgender/transgender" to classify these completely unrelated self-identities as the same kind, simply because their name is or is not consistent with their birth certificate.

Moreover, the cisgender/transgender binary opposition, which synonymises "cisgender" with "non-transgender" @Aultman2014Cisgender@Cava2016Cisgender, fundamentally violates the "principle of self-identification." It is equivalent to assigning a gender identity that aligns their ASAB to anybody who has not explicitly adopted any gender identity label. While, most so-called "cisgender" people have never made such a statement, nor have they ever been asked "What is your gender identity?" This act is almost completely isomorphic to the ASAB; both are top-down, external assignments without consent. #textcite(<Butler2025Who>) said, "Can we decide what being or having a sex means outside of a framework that establishes and reestablishes sex, that is, a framework that has to be imposed with regularity through time, one where the power to self-assign is exercised by those who have already _been_ assigned? Some trans people turn against all assignment, claiming that it invariably works in the service of hierarchy." However, a movement, whose important ethical principle is "opposing non-consensual identity assignment," relies on the non-consensual identity assignment of most people. It repeats the oppressive structure it criticises, and packaging itself in a "critical" language.

The cisgender/transgender binary opposition also implicitly introduces an _a priori_ assumption that "everyone has a gender identity," because the definition of "cisgender/transgender" depends on the existence of it and its agreement with ASAB. By establishing a classification based on "gender identity," it made "having a gender identity" a necessary condition for being a complete-socialised person. If you are not "transgender," then you must be "cisgender" -- people are deprived of the options "null," "undefined," or simply "I don't have this thing at all." //Under this framework, the position of "I have no gender identity" becomes invisible or politically incorrect. Individuals are deprived of the right to "quit the game."
// \footnote{This topic reminds me that I once intended to declare my gender identity as null. I was using it in a very sincere, technical sense (value unassigned). Nevertheless, I immediately realised that I cannot express it like how a computer handles null. When someone asks about my gender identity, I cannot directly throw a "NullPointerException: field \'gender\' not found in object \'user\'" in their brains. In real life, it is still a textual label. The "null" I am writing in this article is four Latin letters, not the technical null.}

Most fatally, when assume all people who have not explicitly stated their gender identity "cisgender," they are saying that all transgender people are cisgender at birth. Because infants are clearly unable to state it, regardless of whether they have one "innately." This is equivalent to saying that "transgender people were cisgender and changed to transgender," which becomes a conservative, transphobic viewpoint. This fallacy is logically and politically devastating.

// "Transgender" is also this kind of imposed identity if we view it from a specific perspective. Some activists and scholars like #textcite(<Zabalegui2024After>) argue that neurological markers are "biological determinism" and strip trans people of their rights. However, if we completely abandon neurological markers, it is effectively saying a person must participate in the social gender construct and have a "gender identity" to get medical treatment. People are striped the right of refusing to participate in gender constructs and identity politics, and just going to a doctor and say, "I have a persistent rejection of this part, it affects my life, and I want to remove it to resolve my suffering." The only reason this isn't the primary path is that the "gender identity" narrative currently has more followers.
